// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: internal/proto/pa_monitor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PaMonitorClient is the client API for PaMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaMonitorClient interface {
	// GetState returns a snapshot of the daemon's current state.
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*DaemonState, error)
	// WatchState streams updates whenever state changes. Idle periods are
	// filled with Heartbeat messages so clients can detect a hung daemon.
	WatchState(ctx context.Context, in *WatchStateRequest, opts ...grpc.CallOption) (PaMonitor_WatchStateClient, error)
	// Ping is a cheap liveness check used by clients to confirm the daemon
	// is responsive before issuing a heavier RPC.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Caffeinate toggles the caffeinate manager. Result reflects the new
	// state. Persisted to runtime.json.
	Caffeinate(ctx context.Context, in *CaffeinateRequest, opts ...grpc.CallOption) (*CaffeinateResponse, error)
	// Nudge sends a signal to one or more session(s) selected by the
	// Selector.
	Nudge(ctx context.Context, in *NudgeRequest, opts ...grpc.CallOption) (*NudgeResponse, error)
	// IsAnyBusy returns whether any agent is currently in the working
	// state. Powers the `agents-busy-check` CLI subcommand.
	IsAnyBusy(ctx context.Context, in *IsAnyBusyRequest, opts ...grpc.CallOption) (*IsAnyBusyResponse, error)
	// GetSessionInfo returns detailed state about one session.
	GetSessionInfo(ctx context.Context, in *GetSessionInfoRequest, opts ...grpc.CallOption) (*SessionDetail, error)
	// GetPathInfo returns the directory rollup for a workspace path.
	GetPathInfo(ctx context.Context, in *GetPathInfoRequest, opts ...grpc.CallOption) (*PathRollup, error)
	// Drain asks the daemon to flush pending telemetry and shut down
	// cleanly. Used for orderly host shutdown.
	Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error)
}

type paMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewPaMonitorClient(cc grpc.ClientConnInterface) PaMonitorClient {
	return &paMonitorClient{cc}
}

func (c *paMonitorClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*DaemonState, error) {
	out := new(DaemonState)
	err := c.cc.Invoke(ctx, "/pa_monitor.v1.PaMonitor/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) WatchState(ctx context.Context, in *WatchStateRequest, opts ...grpc.CallOption) (PaMonitor_WatchStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &PaMonitor_ServiceDesc.Streams[0], "/pa_monitor.v1.PaMonitor/WatchState", opts...)
	if err != nil {
		return nil, err
	}
	x := &paMonitorWatchStateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PaMonitor_WatchStateClient interface {
	Recv() (*WatchStateEvent, error)
	grpc.ClientStream
}

type paMonitorWatchStateClient struct {
	grpc.ClientStream
}

func (x *paMonitorWatchStateClient) Recv() (*WatchStateEvent, error) {
	m := new(WatchStateEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *paMonitorClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/pa_monitor.v1.PaMonitor/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) Caffeinate(ctx context.Context, in *CaffeinateRequest, opts ...grpc.CallOption) (*CaffeinateResponse, error) {
	out := new(CaffeinateResponse)
	err := c.cc.Invoke(ctx, "/pa_monitor.v1.PaMonitor/Caffeinate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) Nudge(ctx context.Context, in *NudgeRequest, opts ...grpc.CallOption) (*NudgeResponse, error) {
	out := new(NudgeResponse)
	err := c.cc.Invoke(ctx, "/pa_monitor.v1.PaMonitor/Nudge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) IsAnyBusy(ctx context.Context, in *IsAnyBusyRequest, opts ...grpc.CallOption) (*IsAnyBusyResponse, error) {
	out := new(IsAnyBusyResponse)
	err := c.cc.Invoke(ctx, "/pa_monitor.v1.PaMonitor/IsAnyBusy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) GetSessionInfo(ctx context.Context, in *GetSessionInfoRequest, opts ...grpc.CallOption) (*SessionDetail, error) {
	out := new(SessionDetail)
	err := c.cc.Invoke(ctx, "/pa_monitor.v1.PaMonitor/GetSessionInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) GetPathInfo(ctx context.Context, in *GetPathInfoRequest, opts ...grpc.CallOption) (*PathRollup, error) {
	out := new(PathRollup)
	err := c.cc.Invoke(ctx, "/pa_monitor.v1.PaMonitor/GetPathInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error) {
	out := new(DrainResponse)
	err := c.cc.Invoke(ctx, "/pa_monitor.v1.PaMonitor/Drain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaMonitorServer is the server API for PaMonitor service.
// All implementations must embed UnimplementedPaMonitorServer
// for forward compatibility
type PaMonitorServer interface {
	// GetState returns a snapshot of the daemon's current state.
	GetState(context.Context, *GetStateRequest) (*DaemonState, error)
	// WatchState streams updates whenever state changes. Idle periods are
	// filled with Heartbeat messages so clients can detect a hung daemon.
	WatchState(*WatchStateRequest, PaMonitor_WatchStateServer) error
	// Ping is a cheap liveness check used by clients to confirm the daemon
	// is responsive before issuing a heavier RPC.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Caffeinate toggles the caffeinate manager. Result reflects the new
	// state. Persisted to runtime.json.
	Caffeinate(context.Context, *CaffeinateRequest) (*CaffeinateResponse, error)
	// Nudge sends a signal to one or more session(s) selected by the
	// Selector.
	Nudge(context.Context, *NudgeRequest) (*NudgeResponse, error)
	// IsAnyBusy returns whether any agent is currently in the working
	// state. Powers the `agents-busy-check` CLI subcommand.
	IsAnyBusy(context.Context, *IsAnyBusyRequest) (*IsAnyBusyResponse, error)
	// GetSessionInfo returns detailed state about one session.
	GetSessionInfo(context.Context, *GetSessionInfoRequest) (*SessionDetail, error)
	// GetPathInfo returns the directory rollup for a workspace path.
	GetPathInfo(context.Context, *GetPathInfoRequest) (*PathRollup, error)
	// Drain asks the daemon to flush pending telemetry and shut down
	// cleanly. Used for orderly host shutdown.
	Drain(context.Context, *DrainRequest) (*DrainResponse, error)
	mustEmbedUnimplementedPaMonitorServer()
}

// UnimplementedPaMonitorServer must be embedded to have forward compatible implementations.
type UnimplementedPaMonitorServer struct {
}

func (UnimplementedPaMonitorServer) GetState(context.Context, *GetStateRequest) (*DaemonState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedPaMonitorServer) WatchState(*WatchStateRequest, PaMonitor_WatchStateServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchState not implemented")
}
func (UnimplementedPaMonitorServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPaMonitorServer) Caffeinate(context.Context, *CaffeinateRequest) (*CaffeinateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Caffeinate not implemented")
}
func (UnimplementedPaMonitorServer) Nudge(context.Context, *NudgeRequest) (*NudgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Nudge not implemented")
}
func (UnimplementedPaMonitorServer) IsAnyBusy(context.Context, *IsAnyBusyRequest) (*IsAnyBusyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAnyBusy not implemented")
}
func (UnimplementedPaMonitorServer) GetSessionInfo(context.Context, *GetSessionInfoRequest) (*SessionDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionInfo not implemented")
}
func (UnimplementedPaMonitorServer) GetPathInfo(context.Context, *GetPathInfoRequest) (*PathRollup, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPathInfo not implemented")
}
func (UnimplementedPaMonitorServer) Drain(context.Context, *DrainRequest) (*DrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Drain not implemented")
}
func (UnimplementedPaMonitorServer) mustEmbedUnimplementedPaMonitorServer() {}

// UnsafePaMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaMonitorServer will
// result in compilation errors.
type UnsafePaMonitorServer interface {
	mustEmbedUnimplementedPaMonitorServer()
}

func RegisterPaMonitorServer(s grpc.ServiceRegistrar, srv PaMonitorServer) {
	s.RegisterService(&PaMonitor_ServiceDesc, srv)
}

func _PaMonitor_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pa_monitor.v1.PaMonitor/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_WatchState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PaMonitorServer).WatchState(m, &paMonitorWatchStateServer{stream})
}

type PaMonitor_WatchStateServer interface {
	Send(*WatchStateEvent) error
	grpc.ServerStream
}

type paMonitorWatchStateServer struct {
	grpc.ServerStream
}

func (x *paMonitorWatchStateServer) Send(m *WatchStateEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _PaMonitor_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pa_monitor.v1.PaMonitor/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_Caffeinate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaffeinateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).Caffeinate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pa_monitor.v1.PaMonitor/Caffeinate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).Caffeinate(ctx, req.(*CaffeinateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_Nudge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NudgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).Nudge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pa_monitor.v1.PaMonitor/Nudge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).Nudge(ctx, req.(*NudgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_IsAnyBusy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAnyBusyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).IsAnyBusy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pa_monitor.v1.PaMonitor/IsAnyBusy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).IsAnyBusy(ctx, req.(*IsAnyBusyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_GetSessionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).GetSessionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pa_monitor.v1.PaMonitor/GetSessionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).GetSessionInfo(ctx, req.(*GetSessionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_GetPathInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPathInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).GetPathInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pa_monitor.v1.PaMonitor/GetPathInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).GetPathInfo(ctx, req.(*GetPathInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_Drain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).Drain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pa_monitor.v1.PaMonitor/Drain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).Drain(ctx, req.(*DrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaMonitor_ServiceDesc is the grpc.ServiceDesc for PaMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pa_monitor.v1.PaMonitor",
	HandlerType: (*PaMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _PaMonitor_GetState_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _PaMonitor_Ping_Handler,
		},
		{
			MethodName: "Caffeinate",
			Handler:    _PaMonitor_Caffeinate_Handler,
		},
		{
			MethodName: "Nudge",
			Handler:    _PaMonitor_Nudge_Handler,
		},
		{
			MethodName: "IsAnyBusy",
			Handler:    _PaMonitor_IsAnyBusy_Handler,
		},
		{
			MethodName: "GetSessionInfo",
			Handler:    _PaMonitor_GetSessionInfo_Handler,
		},
		{
			MethodName: "GetPathInfo",
			Handler:    _PaMonitor_GetPathInfo_Handler,
		},
		{
			MethodName: "Drain",
			Handler:    _PaMonitor_Drain_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchState",
			Handler:       _PaMonitor_WatchState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/proto/pa_monitor.proto",
}
