schema = 3

[mod]
  [mod.'github.com/beorn7/perks']
    version = 'v1.0.1'
    hash = 'sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4='

  [mod.'github.com/cenkalti/backoff/v5']
    version = 'v5.0.3'
    hash = 'sha256-bKq43PPD8RM6e7HePxHaO27traqm76bkvHcTVTQ+jeY='

  [mod.'github.com/cespare/xxhash/v2']
    version = 'v2.3.0'
    hash = 'sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY='

  [mod.'github.com/dustin/go-humanize']
    version = 'v1.0.1'
    hash = 'sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc='

  [mod.'github.com/go-logr/logr']
    version = 'v1.4.3'
    hash = 'sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA='

  [mod.'github.com/go-logr/stdr']
    version = 'v1.2.2'
    hash = 'sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE='

  [mod.'github.com/google/uuid']
    version = 'v1.6.0'
    hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

  [mod.'github.com/grpc-ecosystem/grpc-gateway/v2']
    version = 'v2.29.0'
    hash = 'sha256-a/J/iffTIqbKXIBGGKfPIjgfyb2F05jw3Au8f1q6yEk='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.20'
    hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='

  [mod.'github.com/munnerz/goautoneg']
    version = 'v0.0.0-20191010083416-a7dc8b61c822'
    hash = 'sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q='

  [mod.'github.com/ncruces/go-strftime']
    version = 'v1.0.0'
    hash = 'sha256-GYIwYDONuv/yTE0AEugCHQbtV3oiBaco93xUNYFcVBQ='

  [mod.'github.com/prometheus/client_golang']
    version = 'v1.23.2'
    hash = 'sha256-3GD4fBFa1tJu8MS4TNP6r2re2eViUE+kWUaieIOQXCg='

  [mod.'github.com/prometheus/client_model']
    version = 'v0.6.2'
    hash = 'sha256-q6Fh6v8iNJN9ypD47LjWmx66YITa3FyRjZMRsuRTFeQ='

  [mod.'github.com/prometheus/common']
    version = 'v0.69.0'
    hash = 'sha256-rqui1G7KMtVtGXDFY7XpWD9tA721UtoPC+/JLh8axrA='

  [mod.'github.com/prometheus/procfs']
    version = 'v0.20.1'
    hash = 'sha256-L6RuVGYgdBCCke8BibA7cXgfwizGE2pA0gNo9dGJ8WQ='

  [mod.'github.com/remyoudompheng/bigfft']
    version = 'v0.0.0-20230129092748-24d4a6f8daec'
    hash = 'sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM='

  [mod.'github.com/spf13/cobra']
    version = 'v1.10.2'
    hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'go.opentelemetry.io/auto/sdk']
    version = 'v1.2.1'
    hash = 'sha256-73bFYhnxNf4SfeQ52ebnwOWywdQbqc9lWawCcSgofvE='

  [mod.'go.opentelemetry.io/contrib/bridges/otelslog']
    version = 'v0.19.0'
    hash = 'sha256-wIbFVFbDxPjNyMiz0Flny67B93561uu+pc+Ul3ytWlk='

  [mod.'go.opentelemetry.io/otel']
    version = 'v1.44.0'
    hash = 'sha256-XTGV9RjOIKyWrrgXJ32IA59lovxXqSeRrpcpC1FAFZA='

  [mod.'go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploggrpc']
    version = 'v0.20.0'
    hash = 'sha256-naBnFZNCVipm0xhX/IZLWTDC8jxj3gwpDP9vL6wR3iY='

  [mod.'go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploghttp']
    version = 'v0.20.0'
    hash = 'sha256-HRMfz9VmT9SvYNnTyE9vBbsuSdGj4/MVIByLXaJHn40='

  [mod.'go.opentelemetry.io/otel/exporters/otlp/otlptrace']
    version = 'v1.44.0'
    hash = 'sha256-hqgoY2kWcu58Vdq+DrBZCT0g5bs/cnVLCcwYYWfinu4='

  [mod.'go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc']
    version = 'v1.44.0'
    hash = 'sha256-hQeEeRqWCiMr2m1GHWlIOSbA6YTHgW6EW+M3e26lDn0='

  [mod.'go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp']
    version = 'v1.44.0'
    hash = 'sha256-IOYc4gNOf6DB2f9T1qu1R5jbRM0RhJwpoImmsyUZDSA='

  [mod.'go.opentelemetry.io/otel/log']
    version = 'v0.20.0'
    hash = 'sha256-LUQmrfbnKPHwRgcuX1wlfFDJDiwddOrtbBFHNrMdc+Y='

  [mod.'go.opentelemetry.io/otel/metric']
    version = 'v1.44.0'
    hash = 'sha256-e8dVyRoavby/YG7aH2T05IhWHlLvwnMHyPhelAS1mCQ='

  [mod.'go.opentelemetry.io/otel/sdk']
    version = 'v1.44.0'
    hash = 'sha256-rNqJXr5P2f5Qgllp/3E5Rm5lqt1kBhxHXppT5dXw5Cw='

  [mod.'go.opentelemetry.io/otel/sdk/log']
    version = 'v0.20.0'
    hash = 'sha256-pxmdUm2IQcYaRyxK1CiaSXTdXUnX5gvx8SGmg6giVEE='

  [mod.'go.opentelemetry.io/otel/trace']
    version = 'v1.44.0'
    hash = 'sha256-69HorWRTLLzAHRgLe4nPp13qJthb3qp7RU7c0Y9qV/c='

  [mod.'go.opentelemetry.io/proto/otlp']
    version = 'v1.10.0'
    hash = 'sha256-IEnbR38ucFLTcuC2FA+gRvZNq2loUqXgDskSqP3+LUM='

  [mod.'golang.org/x/net']
    version = 'v0.56.0'
    hash = 'sha256-JUORjxDZqZanYWo2yunaDpQ2/zvHiFb0TnF1Jw6D+30='

  [mod.'golang.org/x/sys']
    version = 'v0.46.0'
    hash = 'sha256-NzRXMSEk6upeudJvUEPVnw6clJ3d8UdC/vdfANWAc8g='

  [mod.'golang.org/x/text']
    version = 'v0.38.0'
    hash = 'sha256-PzREcn7yzTAJ0WBvyYL/2/r+tfoeKTY/E5HVXi/CJsU='

  [mod.'google.golang.org/genproto/googleapis/api']
    version = 'v0.0.0-20260622175928-b703f567277d'
    hash = 'sha256-3iOPS50IPeCzb6h1jvKGvAtGFLOUsQDvImoJUo7PAcY='

  [mod.'google.golang.org/genproto/googleapis/rpc']
    version = 'v0.0.0-20260622175928-b703f567277d'
    hash = 'sha256-ldJTTb7hhj1mdmzTn9IEkQVwCoj3KRlENZtUSEKHABU='

  [mod.'google.golang.org/grpc']
    version = 'v1.81.1'
    hash = 'sha256-YZ5KMHmN1HvsMxyIBIl3SmFmL3r+6bwjzzFLxUFhm1o='

  [mod.'google.golang.org/protobuf']
    version = 'v1.36.11'
    hash = 'sha256-7W+6jntfI/awWL3JP6yQedxqP5S9o3XvPgJ2XxxsIeE='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='

  [mod.'modernc.org/libc']
    version = 'v1.73.4'
    hash = 'sha256-YN3m9MDZ2GRZznT5ErWZJdap+E5xOwOyKlZ/ixyGT+0='

  [mod.'modernc.org/mathutil']
    version = 'v1.7.1'
    hash = 'sha256-COZ5rF2GhQVR1r6a0DanJ8qwQ94JSKdQxTMWrDzE0Cc='

  [mod.'modernc.org/memory']
    version = 'v1.11.0'
    hash = 'sha256-MkybF8vvrxXS5j7O8w3skwTo0aMo1yjWS0K440rYcHM='

  [mod.'modernc.org/sqlite']
    version = 'v1.53.0'
    hash = 'sha256-G8pXCpu2jJlPxd+7p1vQd8GzWGCTnKQug58fnQzTVRY='
