// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/proto/pa_monitor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CaffeinateProcess is the caffeination PROCESS state — what the subprocess
// holding the wake assertion is actually doing. Orthogonal to the
// auto-caffeinate MODE (the user toggle). The incident state was mode:on +
// process:off (armed, not holding); separating the two makes that visible.
type CaffeinateProcess int32

const (
	CaffeinateProcess_CAFFEINATE_PROCESS_OFF   CaffeinateProcess = 0 // not holding any assertion
	CaffeinateProcess_CAFFEINATE_PROCESS_ON    CaffeinateProcess = 1 // holding the wake assertion
	CaffeinateProcess_CAFFEINATE_PROCESS_GRACE CaffeinateProcess = 2 // armed countdown; release pending (see grace_remaining_s)
	CaffeinateProcess_CAFFEINATE_PROCESS_ERROR CaffeinateProcess = 3 // spawn failed; wanted to hold but could not
)

// Enum value maps for CaffeinateProcess.
var (
	CaffeinateProcess_name = map[int32]string{
		0: "CAFFEINATE_PROCESS_OFF",
		1: "CAFFEINATE_PROCESS_ON",
		2: "CAFFEINATE_PROCESS_GRACE",
		3: "CAFFEINATE_PROCESS_ERROR",
	}
	CaffeinateProcess_value = map[string]int32{
		"CAFFEINATE_PROCESS_OFF":   0,
		"CAFFEINATE_PROCESS_ON":    1,
		"CAFFEINATE_PROCESS_GRACE": 2,
		"CAFFEINATE_PROCESS_ERROR": 3,
	}
)

func (x CaffeinateProcess) Enum() *CaffeinateProcess {
	p := new(CaffeinateProcess)
	*p = x
	return p
}

func (x CaffeinateProcess) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaffeinateProcess) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_pa_monitor_proto_enumTypes[0].Descriptor()
}

func (CaffeinateProcess) Type() protoreflect.EnumType {
	return &file_internal_proto_pa_monitor_proto_enumTypes[0]
}

func (x CaffeinateProcess) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaffeinateProcess.Descriptor instead.
func (CaffeinateProcess) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{0}
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{0}
}

type WatchStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Push interval requested by the client, in milliseconds. 0 means
	// "use server default" (2s). Positive values below the server floor
	// (50ms) are clamped to the floor.
	PushIntervalMs uint32 `protobuf:"varint,1,opt,name=push_interval_ms,json=pushIntervalMs,proto3" json:"push_interval_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchStateRequest) Reset() {
	*x = WatchStateRequest{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStateRequest) ProtoMessage() {}

func (x *WatchStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStateRequest.ProtoReflect.Descriptor instead.
func (*WatchStateRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *WatchStateRequest) GetPushIntervalMs() uint32 {
	if x != nil {
		return x.PushIntervalMs
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{2}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

// DaemonState is the full server-rendered view of agent activity that
// clients consume via GetState or WatchState. The shape mirrors
// aggregate.Tree but is stable across daemon versions (the daemon
// translates internal types into this proto).
type DaemonState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Now                 *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=now,proto3" json:"now,omitempty"`
	DaemonUptimeSeconds uint64                 `protobuf:"varint,2,opt,name=daemon_uptime_seconds,json=daemonUptimeSeconds,proto3" json:"daemon_uptime_seconds,omitempty"`
	DaemonVersion       string                 `protobuf:"bytes,3,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	Dirs                []*Directory           `protobuf:"bytes,4,rep,name=dirs,proto3" json:"dirs,omitempty"`
	ActiveBlock         *Block                 `protobuf:"bytes,5,opt,name=active_block,json=activeBlock,proto3" json:"active_block,omitempty"`
	ActiveWeek          *Week                  `protobuf:"bytes,6,opt,name=active_week,json=activeWeek,proto3" json:"active_week,omitempty"`
	// caffeinate_active is the legacy collapsed flag, retained for clients that
	// only need a single bit. New clients should read caffeinate_mode (the user
	// toggle) and caffeinate_process (what the subprocess is doing).
	CaffeinateActive  bool                   `protobuf:"varint,7,opt,name=caffeinate_active,json=caffeinateActive,proto3" json:"caffeinate_active,omitempty"`
	WindowResetsAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=window_resets_at,json=windowResetsAt,proto3" json:"window_resets_at,omitempty"` // earliest pause-reset across sessions
	PlanTier          string                 `protobuf:"bytes,9,opt,name=plan_tier,json=planTier,proto3" json:"plan_tier,omitempty"`
	PlanCapUsd        float64                `protobuf:"fixed64,10,opt,name=plan_cap_usd,json=planCapUsd,proto3" json:"plan_cap_usd,omitempty"`
	WeekCapUsd        float64                `protobuf:"fixed64,11,opt,name=week_cap_usd,json=weekCapUsd,proto3" json:"week_cap_usd,omitempty"`
	CcusageProbed     bool                   `protobuf:"varint,12,opt,name=ccusage_probed,json=ccusageProbed,proto3" json:"ccusage_probed,omitempty"`
	CcusageError      string                 `protobuf:"bytes,13,opt,name=ccusage_error,json=ccusageError,proto3" json:"ccusage_error,omitempty"`
	AutoResumeEnabled bool                   `protobuf:"varint,14,opt,name=auto_resume_enabled,json=autoResumeEnabled,proto3" json:"auto_resume_enabled,omitempty"`
	AutoResumeDelayS  uint32                 `protobuf:"varint,15,opt,name=auto_resume_delay_s,json=autoResumeDelayS,proto3" json:"auto_resume_delay_s,omitempty"`
	// Two unambiguous caffeinate indicators (see CaffeinateProcess).
	CaffeinateMode            bool              `protobuf:"varint,16,opt,name=caffeinate_mode,json=caffeinateMode,proto3" json:"caffeinate_mode,omitempty"`                                               // auto-caffeinate MODE: the user toggle (on/off)
	CaffeinateProcess         CaffeinateProcess `protobuf:"varint,17,opt,name=caffeinate_process,json=caffeinateProcess,proto3,enum=pa_monitor.v1.CaffeinateProcess" json:"caffeinate_process,omitempty"` // caffeination PROCESS state
	CaffeinateGraceRemainingS uint32            `protobuf:"varint,18,opt,name=caffeinate_grace_remaining_s,json=caffeinateGraceRemainingS,proto3" json:"caffeinate_grace_remaining_s,omitempty"`          // seconds left in grace; 0 unless process == GRACE
	CaffeinateCause           string            `protobuf:"bytes,19,opt,name=caffeinate_cause,json=caffeinateCause,proto3" json:"caffeinate_cause,omitempty"`                                             // "manual", "agents_active", or ""
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DaemonState) Reset() {
	*x = DaemonState{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonState) ProtoMessage() {}

func (x *DaemonState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonState.ProtoReflect.Descriptor instead.
func (*DaemonState) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *DaemonState) GetNow() *timestamppb.Timestamp {
	if x != nil {
		return x.Now
	}
	return nil
}

func (x *DaemonState) GetDaemonUptimeSeconds() uint64 {
	if x != nil {
		return x.DaemonUptimeSeconds
	}
	return 0
}

func (x *DaemonState) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *DaemonState) GetDirs() []*Directory {
	if x != nil {
		return x.Dirs
	}
	return nil
}

func (x *DaemonState) GetActiveBlock() *Block {
	if x != nil {
		return x.ActiveBlock
	}
	return nil
}

func (x *DaemonState) GetActiveWeek() *Week {
	if x != nil {
		return x.ActiveWeek
	}
	return nil
}

func (x *DaemonState) GetCaffeinateActive() bool {
	if x != nil {
		return x.CaffeinateActive
	}
	return false
}

func (x *DaemonState) GetWindowResetsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowResetsAt
	}
	return nil
}

func (x *DaemonState) GetPlanTier() string {
	if x != nil {
		return x.PlanTier
	}
	return ""
}

func (x *DaemonState) GetPlanCapUsd() float64 {
	if x != nil {
		return x.PlanCapUsd
	}
	return 0
}

func (x *DaemonState) GetWeekCapUsd() float64 {
	if x != nil {
		return x.WeekCapUsd
	}
	return 0
}

func (x *DaemonState) GetCcusageProbed() bool {
	if x != nil {
		return x.CcusageProbed
	}
	return false
}

func (x *DaemonState) GetCcusageError() string {
	if x != nil {
		return x.CcusageError
	}
	return ""
}

func (x *DaemonState) GetAutoResumeEnabled() bool {
	if x != nil {
		return x.AutoResumeEnabled
	}
	return false
}

func (x *DaemonState) GetAutoResumeDelayS() uint32 {
	if x != nil {
		return x.AutoResumeDelayS
	}
	return 0
}

func (x *DaemonState) GetCaffeinateMode() bool {
	if x != nil {
		return x.CaffeinateMode
	}
	return false
}

func (x *DaemonState) GetCaffeinateProcess() CaffeinateProcess {
	if x != nil {
		return x.CaffeinateProcess
	}
	return CaffeinateProcess_CAFFEINATE_PROCESS_OFF
}

func (x *DaemonState) GetCaffeinateGraceRemainingS() uint32 {
	if x != nil {
		return x.CaffeinateGraceRemainingS
	}
	return 0
}

func (x *DaemonState) GetCaffeinateCause() string {
	if x != nil {
		return x.CaffeinateCause
	}
	return ""
}

type Directory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	PrInfo        *PRInfo                `protobuf:"bytes,3,opt,name=pr_info,json=prInfo,proto3" json:"pr_info,omitempty"`
	Sessions      []*SessionView         `protobuf:"bytes,4,rep,name=sessions,proto3" json:"sessions,omitempty"`
	WorkingN      uint32                 `protobuf:"varint,5,opt,name=working_n,json=workingN,proto3" json:"working_n,omitempty"`
	IdleN         uint32                 `protobuf:"varint,6,opt,name=idle_n,json=idleN,proto3" json:"idle_n,omitempty"`
	DormantN      uint32                 `protobuf:"varint,7,opt,name=dormant_n,json=dormantN,proto3" json:"dormant_n,omitempty"`
	TotalTokens   uint64                 `protobuf:"varint,8,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TotalCostUsd  float64                `protobuf:"fixed64,9,opt,name=total_cost_usd,json=totalCostUsd,proto3" json:"total_cost_usd,omitempty"`
	BurnRateSum   float64                `protobuf:"fixed64,10,opt,name=burn_rate_sum,json=burnRateSum,proto3" json:"burn_rate_sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directory) Reset() {
	*x = Directory{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directory) ProtoMessage() {}

func (x *Directory) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directory.ProtoReflect.Descriptor instead.
func (*Directory) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *Directory) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Directory) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Directory) GetPrInfo() *PRInfo {
	if x != nil {
		return x.PrInfo
	}
	return nil
}

func (x *Directory) GetSessions() []*SessionView {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *Directory) GetWorkingN() uint32 {
	if x != nil {
		return x.WorkingN
	}
	return 0
}

func (x *Directory) GetIdleN() uint32 {
	if x != nil {
		return x.IdleN
	}
	return 0
}

func (x *Directory) GetDormantN() uint32 {
	if x != nil {
		return x.DormantN
	}
	return 0
}

func (x *Directory) GetTotalTokens() uint64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *Directory) GetTotalCostUsd() float64 {
	if x != nil {
		return x.TotalCostUsd
	}
	return 0
}

func (x *Directory) GetBurnRateSum() float64 {
	if x != nil {
		return x.BurnRateSum
	}
	return 0
}

type PRInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint32                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // OPEN, CLOSED, MERGED
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PRInfo) Reset() {
	*x = PRInfo{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PRInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRInfo) ProtoMessage() {}

func (x *PRInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRInfo.ProtoReflect.Descriptor instead.
func (*PRInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{6}
}

func (x *PRInfo) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *PRInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PRInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PRInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SessionView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// identity
	SessionId  string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Pid        uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Cwd        string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Name       string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Kind       string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Entrypoint string                 `protobuf:"bytes,6,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	StartedAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// status
	Status            string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // "working", "idle", "dormant"
	Branch            string                 `protobuf:"bytes,9,opt,name=branch,proto3" json:"branch,omitempty"`
	TerminalHost      string                 `protobuf:"bytes,10,opt,name=terminal_host,json=terminalHost,proto3" json:"terminal_host,omitempty"`
	TranscriptMtime   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=transcript_mtime,json=transcriptMtime,proto3" json:"transcript_mtime,omitempty"`
	RateLimitResetsAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=rate_limit_resets_at,json=rateLimitResetsAt,proto3" json:"rate_limit_resets_at,omitempty"` // zero = not paused
	// enrichment
	ContextTokens uint64  `protobuf:"varint,13,opt,name=context_tokens,json=contextTokens,proto3" json:"context_tokens,omitempty"`
	Model         string  `protobuf:"bytes,14,opt,name=model,proto3" json:"model,omitempty"`
	FirstPrompt   string  `protobuf:"bytes,15,opt,name=first_prompt,json=firstPrompt,proto3" json:"first_prompt,omitempty"`
	SubagentCount uint32  `protobuf:"varint,16,opt,name=subagent_count,json=subagentCount,proto3" json:"subagent_count,omitempty"`
	SubshellCount uint32  `protobuf:"varint,17,opt,name=subshell_count,json=subshellCount,proto3" json:"subshell_count,omitempty"`
	SessionTokens uint64  `protobuf:"varint,18,opt,name=session_tokens,json=sessionTokens,proto3" json:"session_tokens,omitempty"`
	BurnRateShort float64 `protobuf:"fixed64,19,opt,name=burn_rate_short,json=burnRateShort,proto3" json:"burn_rate_short,omitempty"`
	BurnRateLong  float64 `protobuf:"fixed64,20,opt,name=burn_rate_long,json=burnRateLong,proto3" json:"burn_rate_long,omitempty"`
	CostUsd       float64 `protobuf:"fixed64,21,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	AwaitingInput bool    `protobuf:"varint,22,opt,name=awaiting_input,json=awaitingInput,proto3" json:"awaiting_input,omitempty"`
	// Workspace tags pulled from the session's process env. Daemon-side
	// privacy guard: only specific known keys are forwarded; arbitrary
	// env is never wire-exposed. Empty when not present in the env.
	CmuxWorkspaceId string `protobuf:"bytes,23,opt,name=cmux_workspace_id,json=cmuxWorkspaceId,proto3" json:"cmux_workspace_id,omitempty"`
	TmuxSession     string `protobuf:"bytes,24,opt,name=tmux_session,json=tmuxSession,proto3" json:"tmux_session,omitempty"`
	GcRig           string `protobuf:"bytes,25,opt,name=gc_rig,json=gcRig,proto3" json:"gc_rig,omitempty"`
	GcAgent         string `protobuf:"bytes,26,opt,name=gc_agent,json=gcAgent,proto3" json:"gc_agent,omitempty"`
	WorkspaceEnv    string `protobuf:"bytes,27,opt,name=workspace_env,json=workspaceEnv,proto3" json:"workspace_env,omitempty"` // value of $WORKSPACE
	// nudge history (watermarks)
	// Set when the daemon has fired at least one nudge for this session.
	// Both fields are zero/empty when no nudge has ever been delivered.
	LastNudgedAt     *timestamppb.Timestamp `protobuf:"bytes,28,opt,name=last_nudged_at,json=lastNudgedAt,proto3" json:"last_nudged_at,omitempty"`             // wall clock of most recent successful fire
	LastNudgeSources []string               `protobuf:"bytes,29,rep,name=last_nudge_sources,json=lastNudgeSources,proto3" json:"last_nudge_sources,omitempty"` // sources that fired together at last_nudged_at
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionView) Reset() {
	*x = SessionView{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionView) ProtoMessage() {}

func (x *SessionView) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionView.ProtoReflect.Descriptor instead.
func (*SessionView) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *SessionView) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionView) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SessionView) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *SessionView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SessionView) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SessionView) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *SessionView) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SessionView) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionView) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *SessionView) GetTerminalHost() string {
	if x != nil {
		return x.TerminalHost
	}
	return ""
}

func (x *SessionView) GetTranscriptMtime() *timestamppb.Timestamp {
	if x != nil {
		return x.TranscriptMtime
	}
	return nil
}

func (x *SessionView) GetRateLimitResetsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RateLimitResetsAt
	}
	return nil
}

func (x *SessionView) GetContextTokens() uint64 {
	if x != nil {
		return x.ContextTokens
	}
	return 0
}

func (x *SessionView) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SessionView) GetFirstPrompt() string {
	if x != nil {
		return x.FirstPrompt
	}
	return ""
}

func (x *SessionView) GetSubagentCount() uint32 {
	if x != nil {
		return x.SubagentCount
	}
	return 0
}

func (x *SessionView) GetSubshellCount() uint32 {
	if x != nil {
		return x.SubshellCount
	}
	return 0
}

func (x *SessionView) GetSessionTokens() uint64 {
	if x != nil {
		return x.SessionTokens
	}
	return 0
}

func (x *SessionView) GetBurnRateShort() float64 {
	if x != nil {
		return x.BurnRateShort
	}
	return 0
}

func (x *SessionView) GetBurnRateLong() float64 {
	if x != nil {
		return x.BurnRateLong
	}
	return 0
}

func (x *SessionView) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *SessionView) GetAwaitingInput() bool {
	if x != nil {
		return x.AwaitingInput
	}
	return false
}

func (x *SessionView) GetCmuxWorkspaceId() string {
	if x != nil {
		return x.CmuxWorkspaceId
	}
	return ""
}

func (x *SessionView) GetTmuxSession() string {
	if x != nil {
		return x.TmuxSession
	}
	return ""
}

func (x *SessionView) GetGcRig() string {
	if x != nil {
		return x.GcRig
	}
	return ""
}

func (x *SessionView) GetGcAgent() string {
	if x != nil {
		return x.GcAgent
	}
	return ""
}

func (x *SessionView) GetWorkspaceEnv() string {
	if x != nil {
		return x.WorkspaceEnv
	}
	return ""
}

func (x *SessionView) GetLastNudgedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastNudgedAt
	}
	return nil
}

func (x *SessionView) GetLastNudgeSources() []string {
	if x != nil {
		return x.LastNudgeSources
	}
	return nil
}

type Block struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // YYYY-MM-DDTHHZ
	StartTime                  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime                    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsActive                   bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CostUsd                    float64                `protobuf:"fixed64,5,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	TokensPerMinute            float64                `protobuf:"fixed64,6,opt,name=tokens_per_minute,json=tokensPerMinute,proto3" json:"tokens_per_minute,omitempty"`
	CostPerHour                float64                `protobuf:"fixed64,7,opt,name=cost_per_hour,json=costPerHour,proto3" json:"cost_per_hour,omitempty"`
	ProjectionTotalCost        float64                `protobuf:"fixed64,8,opt,name=projection_total_cost,json=projectionTotalCost,proto3" json:"projection_total_cost,omitempty"`
	ProjectionRemainingMinutes uint32                 `protobuf:"varint,9,opt,name=projection_remaining_minutes,json=projectionRemainingMinutes,proto3" json:"projection_remaining_minutes,omitempty"`
	WindowPct                  float64                `protobuf:"fixed64,10,opt,name=window_pct,json=windowPct,proto3" json:"window_pct,omitempty"` // cost_usd / plan_cap_usd
	CapHitAt                   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=cap_hit_at,json=capHitAt,proto3" json:"cap_hit_at,omitempty"`    // when plan cap was first hit; unset if not hit
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{8}
}

func (x *Block) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Block) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Block) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Block) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Block) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *Block) GetTokensPerMinute() float64 {
	if x != nil {
		return x.TokensPerMinute
	}
	return 0
}

func (x *Block) GetCostPerHour() float64 {
	if x != nil {
		return x.CostPerHour
	}
	return 0
}

func (x *Block) GetProjectionTotalCost() float64 {
	if x != nil {
		return x.ProjectionTotalCost
	}
	return 0
}

func (x *Block) GetProjectionRemainingMinutes() uint32 {
	if x != nil {
		return x.ProjectionRemainingMinutes
	}
	return 0
}

func (x *Block) GetWindowPct() float64 {
	if x != nil {
		return x.WindowPct
	}
	return 0
}

func (x *Block) GetCapHitAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapHitAt
	}
	return nil
}

type Week struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // YYYY-Www
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // YYYY-MM-DD (Monday)
	CostUsd       float64                `protobuf:"fixed64,3,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	WindowPct     float64                `protobuf:"fixed64,4,opt,name=window_pct,json=windowPct,proto3" json:"window_pct,omitempty"` // cost_usd / week_cap_usd
	CapHitAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=cap_hit_at,json=capHitAt,proto3" json:"cap_hit_at,omitempty"`    // when week cap was first hit; unset if not hit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Week) Reset() {
	*x = Week{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Week) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Week) ProtoMessage() {}

func (x *Week) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Week.ProtoReflect.Descriptor instead.
func (*Week) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{9}
}

func (x *Week) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Week) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *Week) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *Week) GetWindowPct() float64 {
	if x != nil {
		return x.WindowPct
	}
	return 0
}

func (x *Week) GetCapHitAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapHitAt
	}
	return nil
}

type CaffeinateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action: "on", "off", "toggle". Unknown values return INVALID_ARGUMENT.
	Action        string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaffeinateRequest) Reset() {
	*x = CaffeinateRequest{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaffeinateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaffeinateRequest) ProtoMessage() {}

func (x *CaffeinateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaffeinateRequest.ProtoReflect.Descriptor instead.
func (*CaffeinateRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{10}
}

func (x *CaffeinateRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type CaffeinateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Active          bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`                                            // legacy collapsed flag (mode || process != off)
	Cause           string                 `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`                                               // "manual", "agents_active", or ""
	Until           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`                                               // grace-period expiry (set only while process == GRACE)
	Mode            bool                   `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`                                                // auto-caffeinate MODE: the user toggle after the action
	Process         CaffeinateProcess      `protobuf:"varint,5,opt,name=process,proto3,enum=pa_monitor.v1.CaffeinateProcess" json:"process,omitempty"`     // caffeination PROCESS state after the action
	GraceRemainingS uint32                 `protobuf:"varint,6,opt,name=grace_remaining_s,json=graceRemainingS,proto3" json:"grace_remaining_s,omitempty"` // seconds left in grace; 0 unless process == GRACE
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CaffeinateResponse) Reset() {
	*x = CaffeinateResponse{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaffeinateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaffeinateResponse) ProtoMessage() {}

func (x *CaffeinateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaffeinateResponse.ProtoReflect.Descriptor instead.
func (*CaffeinateResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{11}
}

func (x *CaffeinateResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *CaffeinateResponse) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *CaffeinateResponse) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *CaffeinateResponse) GetMode() bool {
	if x != nil {
		return x.Mode
	}
	return false
}

func (x *CaffeinateResponse) GetProcess() CaffeinateProcess {
	if x != nil {
		return x.Process
	}
	return CaffeinateProcess_CAFFEINATE_PROCESS_OFF
}

func (x *CaffeinateResponse) GetGraceRemainingS() uint32 {
	if x != nil {
		return x.GraceRemainingS
	}
	return 0
}

type Selector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*Selector_SessionId
	//	*Selector_Path
	//	*Selector_CmuxWorkspaceId
	Target        isSelector_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selector) Reset() {
	*x = Selector{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selector) ProtoMessage() {}

func (x *Selector) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selector.ProtoReflect.Descriptor instead.
func (*Selector) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{12}
}

func (x *Selector) GetTarget() isSelector_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Selector) GetSessionId() string {
	if x != nil {
		if x, ok := x.Target.(*Selector_SessionId); ok {
			return x.SessionId
		}
	}
	return ""
}

func (x *Selector) GetPath() string {
	if x != nil {
		if x, ok := x.Target.(*Selector_Path); ok {
			return x.Path
		}
	}
	return ""
}

func (x *Selector) GetCmuxWorkspaceId() string {
	if x != nil {
		if x, ok := x.Target.(*Selector_CmuxWorkspaceId); ok {
			return x.CmuxWorkspaceId
		}
	}
	return ""
}

type isSelector_Target interface {
	isSelector_Target()
}

type Selector_SessionId struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3,oneof"`
}

type Selector_Path struct {
	Path string `protobuf:"bytes,2,opt,name=path,proto3,oneof"`
}

type Selector_CmuxWorkspaceId struct {
	CmuxWorkspaceId string `protobuf:"bytes,3,opt,name=cmux_workspace_id,json=cmuxWorkspaceId,proto3,oneof"`
}

func (*Selector_SessionId) isSelector_Target() {}

func (*Selector_Path) isSelector_Target() {}

func (*Selector_CmuxWorkspaceId) isSelector_Target() {}

type NudgeQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NudgeQueueRequest) Reset() {
	*x = NudgeQueueRequest{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NudgeQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NudgeQueueRequest) ProtoMessage() {}

func (x *NudgeQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NudgeQueueRequest.ProtoReflect.Descriptor instead.
func (*NudgeQueueRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{13}
}

func (x *NudgeQueueRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *NudgeQueueRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type NudgeQueueResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	QueuedSessionIds        []string               `protobuf:"bytes,1,rep,name=queued_session_ids,json=queuedSessionIds,proto3" json:"queued_session_ids,omitempty"`
	AlreadyQueuedSessionIds []string               `protobuf:"bytes,2,rep,name=already_queued_session_ids,json=alreadyQueuedSessionIds,proto3" json:"already_queued_session_ids,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *NudgeQueueResponse) Reset() {
	*x = NudgeQueueResponse{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NudgeQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NudgeQueueResponse) ProtoMessage() {}

func (x *NudgeQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NudgeQueueResponse.ProtoReflect.Descriptor instead.
func (*NudgeQueueResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{14}
}

func (x *NudgeQueueResponse) GetQueuedSessionIds() []string {
	if x != nil {
		return x.QueuedSessionIds
	}
	return nil
}

func (x *NudgeQueueResponse) GetAlreadyQueuedSessionIds() []string {
	if x != nil {
		return x.AlreadyQueuedSessionIds
	}
	return nil
}

type NudgeCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NudgeCancelRequest) Reset() {
	*x = NudgeCancelRequest{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NudgeCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NudgeCancelRequest) ProtoMessage() {}

func (x *NudgeCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NudgeCancelRequest.ProtoReflect.Descriptor instead.
func (*NudgeCancelRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{15}
}

func (x *NudgeCancelRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type NudgeCancelResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CancelledSessionIds []string               `protobuf:"bytes,1,rep,name=cancelled_session_ids,json=cancelledSessionIds,proto3" json:"cancelled_session_ids,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NudgeCancelResponse) Reset() {
	*x = NudgeCancelResponse{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NudgeCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NudgeCancelResponse) ProtoMessage() {}

func (x *NudgeCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NudgeCancelResponse.ProtoReflect.Descriptor instead.
func (*NudgeCancelResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{16}
}

func (x *NudgeCancelResponse) GetCancelledSessionIds() []string {
	if x != nil {
		return x.CancelledSessionIds
	}
	return nil
}

type SetAutoResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAutoResumeRequest) Reset() {
	*x = SetAutoResumeRequest{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAutoResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutoResumeRequest) ProtoMessage() {}

func (x *SetAutoResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutoResumeRequest.ProtoReflect.Descriptor instead.
func (*SetAutoResumeRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{17}
}

func (x *SetAutoResumeRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetAutoResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAutoResumeResponse) Reset() {
	*x = SetAutoResumeResponse{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAutoResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAutoResumeResponse) ProtoMessage() {}

func (x *SetAutoResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAutoResumeResponse.ProtoReflect.Descriptor instead.
func (*SetAutoResumeResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{18}
}

func (x *SetAutoResumeResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// RegisterBridgeRequest carries the bridge's process identity so the
// daemon can walk its ancestry to find the cmux server (parent process
// named "cmux") it belongs to.
type RegisterBridgeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CMUX_WORKSPACE_ID the bridge belongs to. Carried for display / logging;
	// the daemon does not key registry state on this (it keys on cmux server
	// PID derived from bridge_pid).
	WorkspaceId string `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// PID of the bridge process making the call.
	BridgePid     int32 `protobuf:"varint,2,opt,name=bridge_pid,json=bridgePid,proto3" json:"bridge_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBridgeRequest) Reset() {
	*x = RegisterBridgeRequest{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBridgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBridgeRequest) ProtoMessage() {}

func (x *RegisterBridgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBridgeRequest.ProtoReflect.Descriptor instead.
func (*RegisterBridgeRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterBridgeRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *RegisterBridgeRequest) GetBridgePid() int32 {
	if x != nil {
		return x.BridgePid
	}
	return 0
}

type RegisterBridgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBridgeResponse) Reset() {
	*x = RegisterBridgeResponse{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBridgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBridgeResponse) ProtoMessage() {}

func (x *RegisterBridgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBridgeResponse.ProtoReflect.Descriptor instead.
func (*RegisterBridgeResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{20}
}

type ApiError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	IsTerminal    bool                   `protobuf:"varint,4,opt,name=is_terminal,json=isTerminal,proto3" json:"is_terminal,omitempty"`
	IsRetryable   bool                   `protobuf:"varint,5,opt,name=is_retryable,json=isRetryable,proto3" json:"is_retryable,omitempty"`
	FromSubagent  bool                   `protobuf:"varint,6,opt,name=from_subagent,json=fromSubagent,proto3" json:"from_subagent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiError) Reset() {
	*x = ApiError{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiError) ProtoMessage() {}

func (x *ApiError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiError.ProtoReflect.Descriptor instead.
func (*ApiError) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{21}
}

func (x *ApiError) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ApiError) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ApiError) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *ApiError) GetIsTerminal() bool {
	if x != nil {
		return x.IsTerminal
	}
	return false
}

func (x *ApiError) GetIsRetryable() bool {
	if x != nil {
		return x.IsRetryable
	}
	return false
}

func (x *ApiError) GetFromSubagent() bool {
	if x != nil {
		return x.FromSubagent
	}
	return false
}

type PendingNudge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []string               `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingNudge) Reset() {
	*x = PendingNudge{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingNudge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingNudge) ProtoMessage() {}

func (x *PendingNudge) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingNudge.ProtoReflect.Descriptor instead.
func (*PendingNudge) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{22}
}

func (x *PendingNudge) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

type IsAnyBusyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAnyBusyRequest) Reset() {
	*x = IsAnyBusyRequest{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAnyBusyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAnyBusyRequest) ProtoMessage() {}

func (x *IsAnyBusyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAnyBusyRequest.ProtoReflect.Descriptor instead.
func (*IsAnyBusyRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{23}
}

type IsAnyBusyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnyBusy       bool                   `protobuf:"varint,1,opt,name=any_busy,json=anyBusy,proto3" json:"any_busy,omitempty"`
	BusyCount     uint32                 `protobuf:"varint,2,opt,name=busy_count,json=busyCount,proto3" json:"busy_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAnyBusyResponse) Reset() {
	*x = IsAnyBusyResponse{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAnyBusyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAnyBusyResponse) ProtoMessage() {}

func (x *IsAnyBusyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAnyBusyResponse.ProtoReflect.Descriptor instead.
func (*IsAnyBusyResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{24}
}

func (x *IsAnyBusyResponse) GetAnyBusy() bool {
	if x != nil {
		return x.AnyBusy
	}
	return false
}

func (x *IsAnyBusyResponse) GetBusyCount() uint32 {
	if x != nil {
		return x.BusyCount
	}
	return 0
}

type GetSessionInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      *Selector              `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionInfoRequest) Reset() {
	*x = GetSessionInfoRequest{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionInfoRequest) ProtoMessage() {}

func (x *GetSessionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSessionInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{25}
}

func (x *GetSessionInfoRequest) GetSelector() *Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

type SessionDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          *SessionView           `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	LabelPairs    []string               `protobuf:"bytes,2,rep,name=label_pairs,json=labelPairs,proto3" json:"label_pairs,omitempty"`       // "key=value" entries from labels
	LastError     *ApiError              `protobuf:"bytes,3,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`          // most recent API error, if any
	PendingNudge  *PendingNudge          `protobuf:"bytes,4,opt,name=pending_nudge,json=pendingNudge,proto3" json:"pending_nudge,omitempty"` // queued nudge waiting for idle, if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionDetail) Reset() {
	*x = SessionDetail{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDetail) ProtoMessage() {}

func (x *SessionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDetail.ProtoReflect.Descriptor instead.
func (*SessionDetail) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{26}
}

func (x *SessionDetail) GetView() *SessionView {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *SessionDetail) GetLabelPairs() []string {
	if x != nil {
		return x.LabelPairs
	}
	return nil
}

func (x *SessionDetail) GetLastError() *ApiError {
	if x != nil {
		return x.LastError
	}
	return nil
}

func (x *SessionDetail) GetPendingNudge() *PendingNudge {
	if x != nil {
		return x.PendingNudge
	}
	return nil
}

type GetPathInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPathInfoRequest) Reset() {
	*x = GetPathInfoRequest{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPathInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPathInfoRequest) ProtoMessage() {}

func (x *GetPathInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPathInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPathInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{27}
}

func (x *GetPathInfoRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PathRollup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     *Directory             `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathRollup) Reset() {
	*x = PathRollup{}
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathRollup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRollup) ProtoMessage() {}

func (x *PathRollup) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_pa_monitor_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRollup.ProtoReflect.Descriptor instead.
func (*PathRollup) Descriptor() ([]byte, []int) {
	return file_internal_proto_pa_monitor_proto_rawDescGZIP(), []int{28}
}

func (x *PathRollup) GetDirectory() *Directory {
	if x != nil {
		return x.Directory
	}
	return nil
}

var File_internal_proto_pa_monitor_proto protoreflect.FileDescriptor

const file_internal_proto_pa_monitor_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/pa_monitor.proto\x12\rpa_monitor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x11\n" +
	"\x0fGetStateRequest\"=\n" +
	"\x11WatchStateRequest\x12(\n" +
	"\x10push_interval_ms\x18\x01 \x01(\rR\x0epushIntervalMs\"\r\n" +
	"\vPingRequest\":\n" +
	"\fPingResponse\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\"\x98\a\n" +
	"\vDaemonState\x12,\n" +
	"\x03now\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03now\x122\n" +
	"\x15daemon_uptime_seconds\x18\x02 \x01(\x04R\x13daemonUptimeSeconds\x12%\n" +
	"\x0edaemon_version\x18\x03 \x01(\tR\rdaemonVersion\x12,\n" +
	"\x04dirs\x18\x04 \x03(\v2\x18.pa_monitor.v1.DirectoryR\x04dirs\x127\n" +
	"\factive_block\x18\x05 \x01(\v2\x14.pa_monitor.v1.BlockR\vactiveBlock\x124\n" +
	"\vactive_week\x18\x06 \x01(\v2\x13.pa_monitor.v1.WeekR\n" +
	"activeWeek\x12+\n" +
	"\x11caffeinate_active\x18\a \x01(\bR\x10caffeinateActive\x12D\n" +
	"\x10window_resets_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0ewindowResetsAt\x12\x1b\n" +
	"\tplan_tier\x18\t \x01(\tR\bplanTier\x12 \n" +
	"\fplan_cap_usd\x18\n" +
	" \x01(\x01R\n" +
	"planCapUsd\x12 \n" +
	"\fweek_cap_usd\x18\v \x01(\x01R\n" +
	"weekCapUsd\x12%\n" +
	"\x0eccusage_probed\x18\f \x01(\bR\rccusageProbed\x12#\n" +
	"\rccusage_error\x18\r \x01(\tR\fccusageError\x12.\n" +
	"\x13auto_resume_enabled\x18\x0e \x01(\bR\x11autoResumeEnabled\x12-\n" +
	"\x13auto_resume_delay_s\x18\x0f \x01(\rR\x10autoResumeDelayS\x12'\n" +
	"\x0fcaffeinate_mode\x18\x10 \x01(\bR\x0ecaffeinateMode\x12O\n" +
	"\x12caffeinate_process\x18\x11 \x01(\x0e2 .pa_monitor.v1.CaffeinateProcessR\x11caffeinateProcess\x12?\n" +
	"\x1ccaffeinate_grace_remaining_s\x18\x12 \x01(\rR\x19caffeinateGraceRemainingS\x12)\n" +
	"\x10caffeinate_cause\x18\x13 \x01(\tR\x0fcaffeinateCause\"\xdd\x02\n" +
	"\tDirectory\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12.\n" +
	"\apr_info\x18\x03 \x01(\v2\x15.pa_monitor.v1.PRInfoR\x06prInfo\x126\n" +
	"\bsessions\x18\x04 \x03(\v2\x1a.pa_monitor.v1.SessionViewR\bsessions\x12\x1b\n" +
	"\tworking_n\x18\x05 \x01(\rR\bworkingN\x12\x15\n" +
	"\x06idle_n\x18\x06 \x01(\rR\x05idleN\x12\x1b\n" +
	"\tdormant_n\x18\a \x01(\rR\bdormantN\x12!\n" +
	"\ftotal_tokens\x18\b \x01(\x04R\vtotalTokens\x12$\n" +
	"\x0etotal_cost_usd\x18\t \x01(\x01R\ftotalCostUsd\x12\"\n" +
	"\rburn_rate_sum\x18\n" +
	" \x01(\x01R\vburnRateSum\"^\n" +
	"\x06PRInfo\x12\x16\n" +
	"\x06number\x18\x01 \x01(\rR\x06number\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"\xb7\b\n" +
	"\vSessionView\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x06 \x01(\tR\n" +
	"entrypoint\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x16\n" +
	"\x06branch\x18\t \x01(\tR\x06branch\x12#\n" +
	"\rterminal_host\x18\n" +
	" \x01(\tR\fterminalHost\x12E\n" +
	"\x10transcript_mtime\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0ftranscriptMtime\x12K\n" +
	"\x14rate_limit_resets_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x11rateLimitResetsAt\x12%\n" +
	"\x0econtext_tokens\x18\r \x01(\x04R\rcontextTokens\x12\x14\n" +
	"\x05model\x18\x0e \x01(\tR\x05model\x12!\n" +
	"\ffirst_prompt\x18\x0f \x01(\tR\vfirstPrompt\x12%\n" +
	"\x0esubagent_count\x18\x10 \x01(\rR\rsubagentCount\x12%\n" +
	"\x0esubshell_count\x18\x11 \x01(\rR\rsubshellCount\x12%\n" +
	"\x0esession_tokens\x18\x12 \x01(\x04R\rsessionTokens\x12&\n" +
	"\x0fburn_rate_short\x18\x13 \x01(\x01R\rburnRateShort\x12$\n" +
	"\x0eburn_rate_long\x18\x14 \x01(\x01R\fburnRateLong\x12\x19\n" +
	"\bcost_usd\x18\x15 \x01(\x01R\acostUsd\x12%\n" +
	"\x0eawaiting_input\x18\x16 \x01(\bR\rawaitingInput\x12*\n" +
	"\x11cmux_workspace_id\x18\x17 \x01(\tR\x0fcmuxWorkspaceId\x12!\n" +
	"\ftmux_session\x18\x18 \x01(\tR\vtmuxSession\x12\x15\n" +
	"\x06gc_rig\x18\x19 \x01(\tR\x05gcRig\x12\x19\n" +
	"\bgc_agent\x18\x1a \x01(\tR\agcAgent\x12#\n" +
	"\rworkspace_env\x18\x1b \x01(\tR\fworkspaceEnv\x12@\n" +
	"\x0elast_nudged_at\x18\x1c \x01(\v2\x1a.google.protobuf.TimestampR\flastNudgedAt\x12,\n" +
	"\x12last_nudge_sources\x18\x1d \x03(\tR\x10lastNudgeSources\"\xe0\x03\n" +
	"\x05Block\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x19\n" +
	"\bcost_usd\x18\x05 \x01(\x01R\acostUsd\x12*\n" +
	"\x11tokens_per_minute\x18\x06 \x01(\x01R\x0ftokensPerMinute\x12\"\n" +
	"\rcost_per_hour\x18\a \x01(\x01R\vcostPerHour\x122\n" +
	"\x15projection_total_cost\x18\b \x01(\x01R\x13projectionTotalCost\x12@\n" +
	"\x1cprojection_remaining_minutes\x18\t \x01(\rR\x1aprojectionRemainingMinutes\x12\x1d\n" +
	"\n" +
	"window_pct\x18\n" +
	" \x01(\x01R\twindowPct\x128\n" +
	"\n" +
	"cap_hit_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bcapHitAt\"\xa2\x01\n" +
	"\x04Week\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x12\x19\n" +
	"\bcost_usd\x18\x03 \x01(\x01R\acostUsd\x12\x1d\n" +
	"\n" +
	"window_pct\x18\x04 \x01(\x01R\twindowPct\x128\n" +
	"\n" +
	"cap_hit_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bcapHitAt\"+\n" +
	"\x11CaffeinateRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\"\xf0\x01\n" +
	"\x12CaffeinateResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x14\n" +
	"\x05cause\x18\x02 \x01(\tR\x05cause\x120\n" +
	"\x05until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\bR\x04mode\x12:\n" +
	"\aprocess\x18\x05 \x01(\x0e2 .pa_monitor.v1.CaffeinateProcessR\aprocess\x12*\n" +
	"\x11grace_remaining_s\x18\x06 \x01(\rR\x0fgraceRemainingS\"y\n" +
	"\bSelector\x12\x1f\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tH\x00R\tsessionId\x12\x14\n" +
	"\x04path\x18\x02 \x01(\tH\x00R\x04path\x12,\n" +
	"\x11cmux_workspace_id\x18\x03 \x01(\tH\x00R\x0fcmuxWorkspaceIdB\b\n" +
	"\x06target\"C\n" +
	"\x11NudgeQueueRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x7f\n" +
	"\x12NudgeQueueResponse\x12,\n" +
	"\x12queued_session_ids\x18\x01 \x03(\tR\x10queuedSessionIds\x12;\n" +
	"\x1aalready_queued_session_ids\x18\x02 \x03(\tR\x17alreadyQueuedSessionIds\"0\n" +
	"\x12NudgeCancelRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\"I\n" +
	"\x13NudgeCancelResponse\x122\n" +
	"\x15cancelled_session_ids\x18\x01 \x03(\tR\x13cancelledSessionIds\"0\n" +
	"\x14SetAutoResumeRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"1\n" +
	"\x15SetAutoResumeResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"Y\n" +
	"\x15RegisterBridgeRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"bridge_pid\x18\x02 \x01(\x05R\tbridgePid\"\x18\n" +
	"\x16RegisterBridgeResponse\"\xc7\x01\n" +
	"\bApiError\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x1f\n" +
	"\vis_terminal\x18\x04 \x01(\bR\n" +
	"isTerminal\x12!\n" +
	"\fis_retryable\x18\x05 \x01(\bR\visRetryable\x12#\n" +
	"\rfrom_subagent\x18\x06 \x01(\bR\ffromSubagent\"(\n" +
	"\fPendingNudge\x12\x18\n" +
	"\asources\x18\x01 \x03(\tR\asources\"\x12\n" +
	"\x10IsAnyBusyRequest\"M\n" +
	"\x11IsAnyBusyResponse\x12\x19\n" +
	"\bany_busy\x18\x01 \x01(\bR\aanyBusy\x12\x1d\n" +
	"\n" +
	"busy_count\x18\x02 \x01(\rR\tbusyCount\"L\n" +
	"\x15GetSessionInfoRequest\x123\n" +
	"\bselector\x18\x01 \x01(\v2\x17.pa_monitor.v1.SelectorR\bselector\"\xda\x01\n" +
	"\rSessionDetail\x12.\n" +
	"\x04view\x18\x01 \x01(\v2\x1a.pa_monitor.v1.SessionViewR\x04view\x12\x1f\n" +
	"\vlabel_pairs\x18\x02 \x03(\tR\n" +
	"labelPairs\x126\n" +
	"\n" +
	"last_error\x18\x03 \x01(\v2\x17.pa_monitor.v1.ApiErrorR\tlastError\x12@\n" +
	"\rpending_nudge\x18\x04 \x01(\v2\x1b.pa_monitor.v1.PendingNudgeR\fpendingNudge\"(\n" +
	"\x12GetPathInfoRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"D\n" +
	"\n" +
	"PathRollup\x126\n" +
	"\tdirectory\x18\x01 \x01(\v2\x18.pa_monitor.v1.DirectoryR\tdirectory*\x86\x01\n" +
	"\x11CaffeinateProcess\x12\x1a\n" +
	"\x16CAFFEINATE_PROCESS_OFF\x10\x00\x12\x19\n" +
	"\x15CAFFEINATE_PROCESS_ON\x10\x01\x12\x1c\n" +
	"\x18CAFFEINATE_PROCESS_GRACE\x10\x02\x12\x1c\n" +
	"\x18CAFFEINATE_PROCESS_ERROR\x10\x032\x8c\a\n" +
	"\tPaMonitor\x12F\n" +
	"\bGetState\x12\x1e.pa_monitor.v1.GetStateRequest\x1a\x1a.pa_monitor.v1.DaemonState\x12L\n" +
	"\n" +
	"WatchState\x12 .pa_monitor.v1.WatchStateRequest\x1a\x1a.pa_monitor.v1.DaemonState0\x01\x12?\n" +
	"\x04Ping\x12\x1a.pa_monitor.v1.PingRequest\x1a\x1b.pa_monitor.v1.PingResponse\x12Q\n" +
	"\n" +
	"Caffeinate\x12 .pa_monitor.v1.CaffeinateRequest\x1a!.pa_monitor.v1.CaffeinateResponse\x12N\n" +
	"\tIsAnyBusy\x12\x1f.pa_monitor.v1.IsAnyBusyRequest\x1a .pa_monitor.v1.IsAnyBusyResponse\x12T\n" +
	"\x0eGetSessionInfo\x12$.pa_monitor.v1.GetSessionInfoRequest\x1a\x1c.pa_monitor.v1.SessionDetail\x12K\n" +
	"\vGetPathInfo\x12!.pa_monitor.v1.GetPathInfoRequest\x1a\x19.pa_monitor.v1.PathRollup\x12Q\n" +
	"\n" +
	"NudgeQueue\x12 .pa_monitor.v1.NudgeQueueRequest\x1a!.pa_monitor.v1.NudgeQueueResponse\x12T\n" +
	"\vNudgeCancel\x12!.pa_monitor.v1.NudgeCancelRequest\x1a\".pa_monitor.v1.NudgeCancelResponse\x12Z\n" +
	"\rSetAutoResume\x12#.pa_monitor.v1.SetAutoResumeRequest\x1a$.pa_monitor.v1.SetAutoResumeResponse\x12]\n" +
	"\x0eRegisterBridge\x12$.pa_monitor.v1.RegisterBridgeRequest\x1a%.pa_monitor.v1.RegisterBridgeResponseB;Z9github.com/phillipgreenii/pa-monitor/internal/proto;protob\x06proto3"

var (
	file_internal_proto_pa_monitor_proto_rawDescOnce sync.Once
	file_internal_proto_pa_monitor_proto_rawDescData []byte
)

func file_internal_proto_pa_monitor_proto_rawDescGZIP() []byte {
	file_internal_proto_pa_monitor_proto_rawDescOnce.Do(func() {
		file_internal_proto_pa_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_pa_monitor_proto_rawDesc), len(file_internal_proto_pa_monitor_proto_rawDesc)))
	})
	return file_internal_proto_pa_monitor_proto_rawDescData
}

var file_internal_proto_pa_monitor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_pa_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_internal_proto_pa_monitor_proto_goTypes = []any{
	(CaffeinateProcess)(0),         // 0: pa_monitor.v1.CaffeinateProcess
	(*GetStateRequest)(nil),        // 1: pa_monitor.v1.GetStateRequest
	(*WatchStateRequest)(nil),      // 2: pa_monitor.v1.WatchStateRequest
	(*PingRequest)(nil),            // 3: pa_monitor.v1.PingRequest
	(*PingResponse)(nil),           // 4: pa_monitor.v1.PingResponse
	(*DaemonState)(nil),            // 5: pa_monitor.v1.DaemonState
	(*Directory)(nil),              // 6: pa_monitor.v1.Directory
	(*PRInfo)(nil),                 // 7: pa_monitor.v1.PRInfo
	(*SessionView)(nil),            // 8: pa_monitor.v1.SessionView
	(*Block)(nil),                  // 9: pa_monitor.v1.Block
	(*Week)(nil),                   // 10: pa_monitor.v1.Week
	(*CaffeinateRequest)(nil),      // 11: pa_monitor.v1.CaffeinateRequest
	(*CaffeinateResponse)(nil),     // 12: pa_monitor.v1.CaffeinateResponse
	(*Selector)(nil),               // 13: pa_monitor.v1.Selector
	(*NudgeQueueRequest)(nil),      // 14: pa_monitor.v1.NudgeQueueRequest
	(*NudgeQueueResponse)(nil),     // 15: pa_monitor.v1.NudgeQueueResponse
	(*NudgeCancelRequest)(nil),     // 16: pa_monitor.v1.NudgeCancelRequest
	(*NudgeCancelResponse)(nil),    // 17: pa_monitor.v1.NudgeCancelResponse
	(*SetAutoResumeRequest)(nil),   // 18: pa_monitor.v1.SetAutoResumeRequest
	(*SetAutoResumeResponse)(nil),  // 19: pa_monitor.v1.SetAutoResumeResponse
	(*RegisterBridgeRequest)(nil),  // 20: pa_monitor.v1.RegisterBridgeRequest
	(*RegisterBridgeResponse)(nil), // 21: pa_monitor.v1.RegisterBridgeResponse
	(*ApiError)(nil),               // 22: pa_monitor.v1.ApiError
	(*PendingNudge)(nil),           // 23: pa_monitor.v1.PendingNudge
	(*IsAnyBusyRequest)(nil),       // 24: pa_monitor.v1.IsAnyBusyRequest
	(*IsAnyBusyResponse)(nil),      // 25: pa_monitor.v1.IsAnyBusyResponse
	(*GetSessionInfoRequest)(nil),  // 26: pa_monitor.v1.GetSessionInfoRequest
	(*SessionDetail)(nil),          // 27: pa_monitor.v1.SessionDetail
	(*GetPathInfoRequest)(nil),     // 28: pa_monitor.v1.GetPathInfoRequest
	(*PathRollup)(nil),             // 29: pa_monitor.v1.PathRollup
	(*timestamppb.Timestamp)(nil),  // 30: google.protobuf.Timestamp
}
var file_internal_proto_pa_monitor_proto_depIdxs = []int32{
	30, // 0: pa_monitor.v1.PingResponse.ts:type_name -> google.protobuf.Timestamp
	30, // 1: pa_monitor.v1.DaemonState.now:type_name -> google.protobuf.Timestamp
	6,  // 2: pa_monitor.v1.DaemonState.dirs:type_name -> pa_monitor.v1.Directory
	9,  // 3: pa_monitor.v1.DaemonState.active_block:type_name -> pa_monitor.v1.Block
	10, // 4: pa_monitor.v1.DaemonState.active_week:type_name -> pa_monitor.v1.Week
	30, // 5: pa_monitor.v1.DaemonState.window_resets_at:type_name -> google.protobuf.Timestamp
	0,  // 6: pa_monitor.v1.DaemonState.caffeinate_process:type_name -> pa_monitor.v1.CaffeinateProcess
	7,  // 7: pa_monitor.v1.Directory.pr_info:type_name -> pa_monitor.v1.PRInfo
	8,  // 8: pa_monitor.v1.Directory.sessions:type_name -> pa_monitor.v1.SessionView
	30, // 9: pa_monitor.v1.SessionView.started_at:type_name -> google.protobuf.Timestamp
	30, // 10: pa_monitor.v1.SessionView.transcript_mtime:type_name -> google.protobuf.Timestamp
	30, // 11: pa_monitor.v1.SessionView.rate_limit_resets_at:type_name -> google.protobuf.Timestamp
	30, // 12: pa_monitor.v1.SessionView.last_nudged_at:type_name -> google.protobuf.Timestamp
	30, // 13: pa_monitor.v1.Block.start_time:type_name -> google.protobuf.Timestamp
	30, // 14: pa_monitor.v1.Block.end_time:type_name -> google.protobuf.Timestamp
	30, // 15: pa_monitor.v1.Block.cap_hit_at:type_name -> google.protobuf.Timestamp
	30, // 16: pa_monitor.v1.Week.cap_hit_at:type_name -> google.protobuf.Timestamp
	30, // 17: pa_monitor.v1.CaffeinateResponse.until:type_name -> google.protobuf.Timestamp
	0,  // 18: pa_monitor.v1.CaffeinateResponse.process:type_name -> pa_monitor.v1.CaffeinateProcess
	30, // 19: pa_monitor.v1.ApiError.at:type_name -> google.protobuf.Timestamp
	13, // 20: pa_monitor.v1.GetSessionInfoRequest.selector:type_name -> pa_monitor.v1.Selector
	8,  // 21: pa_monitor.v1.SessionDetail.view:type_name -> pa_monitor.v1.SessionView
	22, // 22: pa_monitor.v1.SessionDetail.last_error:type_name -> pa_monitor.v1.ApiError
	23, // 23: pa_monitor.v1.SessionDetail.pending_nudge:type_name -> pa_monitor.v1.PendingNudge
	6,  // 24: pa_monitor.v1.PathRollup.directory:type_name -> pa_monitor.v1.Directory
	1,  // 25: pa_monitor.v1.PaMonitor.GetState:input_type -> pa_monitor.v1.GetStateRequest
	2,  // 26: pa_monitor.v1.PaMonitor.WatchState:input_type -> pa_monitor.v1.WatchStateRequest
	3,  // 27: pa_monitor.v1.PaMonitor.Ping:input_type -> pa_monitor.v1.PingRequest
	11, // 28: pa_monitor.v1.PaMonitor.Caffeinate:input_type -> pa_monitor.v1.CaffeinateRequest
	24, // 29: pa_monitor.v1.PaMonitor.IsAnyBusy:input_type -> pa_monitor.v1.IsAnyBusyRequest
	26, // 30: pa_monitor.v1.PaMonitor.GetSessionInfo:input_type -> pa_monitor.v1.GetSessionInfoRequest
	28, // 31: pa_monitor.v1.PaMonitor.GetPathInfo:input_type -> pa_monitor.v1.GetPathInfoRequest
	14, // 32: pa_monitor.v1.PaMonitor.NudgeQueue:input_type -> pa_monitor.v1.NudgeQueueRequest
	16, // 33: pa_monitor.v1.PaMonitor.NudgeCancel:input_type -> pa_monitor.v1.NudgeCancelRequest
	18, // 34: pa_monitor.v1.PaMonitor.SetAutoResume:input_type -> pa_monitor.v1.SetAutoResumeRequest
	20, // 35: pa_monitor.v1.PaMonitor.RegisterBridge:input_type -> pa_monitor.v1.RegisterBridgeRequest
	5,  // 36: pa_monitor.v1.PaMonitor.GetState:output_type -> pa_monitor.v1.DaemonState
	5,  // 37: pa_monitor.v1.PaMonitor.WatchState:output_type -> pa_monitor.v1.DaemonState
	4,  // 38: pa_monitor.v1.PaMonitor.Ping:output_type -> pa_monitor.v1.PingResponse
	12, // 39: pa_monitor.v1.PaMonitor.Caffeinate:output_type -> pa_monitor.v1.CaffeinateResponse
	25, // 40: pa_monitor.v1.PaMonitor.IsAnyBusy:output_type -> pa_monitor.v1.IsAnyBusyResponse
	27, // 41: pa_monitor.v1.PaMonitor.GetSessionInfo:output_type -> pa_monitor.v1.SessionDetail
	29, // 42: pa_monitor.v1.PaMonitor.GetPathInfo:output_type -> pa_monitor.v1.PathRollup
	15, // 43: pa_monitor.v1.PaMonitor.NudgeQueue:output_type -> pa_monitor.v1.NudgeQueueResponse
	17, // 44: pa_monitor.v1.PaMonitor.NudgeCancel:output_type -> pa_monitor.v1.NudgeCancelResponse
	19, // 45: pa_monitor.v1.PaMonitor.SetAutoResume:output_type -> pa_monitor.v1.SetAutoResumeResponse
	21, // 46: pa_monitor.v1.PaMonitor.RegisterBridge:output_type -> pa_monitor.v1.RegisterBridgeResponse
	36, // [36:47] is the sub-list for method output_type
	25, // [25:36] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_internal_proto_pa_monitor_proto_init() }
func file_internal_proto_pa_monitor_proto_init() {
	if File_internal_proto_pa_monitor_proto != nil {
		return
	}
	file_internal_proto_pa_monitor_proto_msgTypes[12].OneofWrappers = []any{
		(*Selector_SessionId)(nil),
		(*Selector_Path)(nil),
		(*Selector_CmuxWorkspaceId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_pa_monitor_proto_rawDesc), len(file_internal_proto_pa_monitor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_pa_monitor_proto_goTypes,
		DependencyIndexes: file_internal_proto_pa_monitor_proto_depIdxs,
		EnumInfos:         file_internal_proto_pa_monitor_proto_enumTypes,
		MessageInfos:      file_internal_proto_pa_monitor_proto_msgTypes,
	}.Build()
	File_internal_proto_pa_monitor_proto = out.File
	file_internal_proto_pa_monitor_proto_goTypes = nil
	file_internal_proto_pa_monitor_proto_depIdxs = nil
}
