// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: internal/proto/pa_monitor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaMonitor_GetState_FullMethodName       = "/pa_monitor.v1.PaMonitor/GetState"
	PaMonitor_WatchState_FullMethodName     = "/pa_monitor.v1.PaMonitor/WatchState"
	PaMonitor_Ping_FullMethodName           = "/pa_monitor.v1.PaMonitor/Ping"
	PaMonitor_Caffeinate_FullMethodName     = "/pa_monitor.v1.PaMonitor/Caffeinate"
	PaMonitor_IsAnyBusy_FullMethodName      = "/pa_monitor.v1.PaMonitor/IsAnyBusy"
	PaMonitor_GetSessionInfo_FullMethodName = "/pa_monitor.v1.PaMonitor/GetSessionInfo"
	PaMonitor_GetPathInfo_FullMethodName    = "/pa_monitor.v1.PaMonitor/GetPathInfo"
	PaMonitor_NudgeQueue_FullMethodName     = "/pa_monitor.v1.PaMonitor/NudgeQueue"
	PaMonitor_NudgeCancel_FullMethodName    = "/pa_monitor.v1.PaMonitor/NudgeCancel"
	PaMonitor_SetAutoResume_FullMethodName  = "/pa_monitor.v1.PaMonitor/SetAutoResume"
	PaMonitor_RegisterBridge_FullMethodName = "/pa_monitor.v1.PaMonitor/RegisterBridge"
	PaMonitor_BridgeChannel_FullMethodName  = "/pa_monitor.v1.PaMonitor/BridgeChannel"
)

// PaMonitorClient is the client API for PaMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PaMonitor is the daemon's gRPC surface. Clients (TUI, CLI, cmux-bridge)
// use it to observe state and to drive daemon-owned operations
// (caffeinate, nudge, etc.).
type PaMonitorClient interface {
	// GetState returns a snapshot of the daemon's current state.
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*DaemonState, error)
	// WatchState streams DaemonState updates. The daemon pushes a fresh
	// state on every tick (interval requested via push_interval_ms, with
	// a 250ms server floor and a 2s default). Each push is a full DB
	// materialization, so the floor bounds the worst-case snapshot rate a
	// single client can force. Subscribers detect a hung daemon by missing
	// pushes within their own watchdog budget.
	WatchState(ctx context.Context, in *WatchStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DaemonState], error)
	// Ping is a cheap liveness check used by clients to confirm the daemon
	// is responsive before issuing a heavier RPC.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Caffeinate toggles the caffeinate manager. Result reflects the new
	// state. Persisted to runtime.json.
	Caffeinate(ctx context.Context, in *CaffeinateRequest, opts ...grpc.CallOption) (*CaffeinateResponse, error)
	// IsAnyBusy returns whether any agent is currently in the working
	// state. Powers the `agents-busy-check` CLI subcommand.
	IsAnyBusy(ctx context.Context, in *IsAnyBusyRequest, opts ...grpc.CallOption) (*IsAnyBusyResponse, error)
	// GetSessionInfo returns detailed state about one session.
	GetSessionInfo(ctx context.Context, in *GetSessionInfoRequest, opts ...grpc.CallOption) (*SessionDetail, error)
	// GetPathInfo returns the directory rollup for a workspace path.
	GetPathInfo(ctx context.Context, in *GetPathInfoRequest, opts ...grpc.CallOption) (*PathRollup, error)
	// NudgeQueue enqueues a nudge to be sent when a session next becomes idle.
	NudgeQueue(ctx context.Context, in *NudgeQueueRequest, opts ...grpc.CallOption) (*NudgeQueueResponse, error)
	// NudgeCancel cancels a previously queued nudge.
	NudgeCancel(ctx context.Context, in *NudgeCancelRequest, opts ...grpc.CallOption) (*NudgeCancelResponse, error)
	// SetAutoResume toggles the auto-resume feature daemon-wide.
	SetAutoResume(ctx context.Context, in *SetAutoResumeRequest, opts ...grpc.CallOption) (*SetAutoResumeResponse, error)
	// RegisterBridge announces a cmux-bridge to the daemon. Called by
	// cmux-bridge on startup and as a periodic heartbeat. The daemon uses
	// bridge_pid to derive the bridge's cmux server (parent ancestor named
	// "cmux") and tracks last-seen so it can surface session terminal status
	// (cmux vs. cmux-no-bridge vs. cmux-bridge-disconnected) for sessions in
	// the same cmux workspace.
	RegisterBridge(ctx context.Context, in *RegisterBridgeRequest, opts ...grpc.CallOption) (*RegisterBridgeResponse, error)
	// BridgeChannel is a bidirectional stream between a cmux-bridge and the
	// daemon: the bridge sends Register/Heartbeat/DeliverResult messages, and
	// the daemon pushes DaemonState snapshots and Deliver (nudge delivery)
	// requests.
	BridgeChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BridgeMsg, DaemonMsg], error)
}

type paMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewPaMonitorClient(cc grpc.ClientConnInterface) PaMonitorClient {
	return &paMonitorClient{cc}
}

func (c *paMonitorClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*DaemonState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonState)
	err := c.cc.Invoke(ctx, PaMonitor_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) WatchState(ctx context.Context, in *WatchStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DaemonState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PaMonitor_ServiceDesc.Streams[0], PaMonitor_WatchState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchStateRequest, DaemonState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PaMonitor_WatchStateClient = grpc.ServerStreamingClient[DaemonState]

func (c *paMonitorClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, PaMonitor_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) Caffeinate(ctx context.Context, in *CaffeinateRequest, opts ...grpc.CallOption) (*CaffeinateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaffeinateResponse)
	err := c.cc.Invoke(ctx, PaMonitor_Caffeinate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) IsAnyBusy(ctx context.Context, in *IsAnyBusyRequest, opts ...grpc.CallOption) (*IsAnyBusyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsAnyBusyResponse)
	err := c.cc.Invoke(ctx, PaMonitor_IsAnyBusy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) GetSessionInfo(ctx context.Context, in *GetSessionInfoRequest, opts ...grpc.CallOption) (*SessionDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionDetail)
	err := c.cc.Invoke(ctx, PaMonitor_GetSessionInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) GetPathInfo(ctx context.Context, in *GetPathInfoRequest, opts ...grpc.CallOption) (*PathRollup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PathRollup)
	err := c.cc.Invoke(ctx, PaMonitor_GetPathInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) NudgeQueue(ctx context.Context, in *NudgeQueueRequest, opts ...grpc.CallOption) (*NudgeQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NudgeQueueResponse)
	err := c.cc.Invoke(ctx, PaMonitor_NudgeQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) NudgeCancel(ctx context.Context, in *NudgeCancelRequest, opts ...grpc.CallOption) (*NudgeCancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NudgeCancelResponse)
	err := c.cc.Invoke(ctx, PaMonitor_NudgeCancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) SetAutoResume(ctx context.Context, in *SetAutoResumeRequest, opts ...grpc.CallOption) (*SetAutoResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAutoResumeResponse)
	err := c.cc.Invoke(ctx, PaMonitor_SetAutoResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) RegisterBridge(ctx context.Context, in *RegisterBridgeRequest, opts ...grpc.CallOption) (*RegisterBridgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterBridgeResponse)
	err := c.cc.Invoke(ctx, PaMonitor_RegisterBridge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paMonitorClient) BridgeChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BridgeMsg, DaemonMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PaMonitor_ServiceDesc.Streams[1], PaMonitor_BridgeChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BridgeMsg, DaemonMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PaMonitor_BridgeChannelClient = grpc.BidiStreamingClient[BridgeMsg, DaemonMsg]

// PaMonitorServer is the server API for PaMonitor service.
// All implementations must embed UnimplementedPaMonitorServer
// for forward compatibility.
//
// PaMonitor is the daemon's gRPC surface. Clients (TUI, CLI, cmux-bridge)
// use it to observe state and to drive daemon-owned operations
// (caffeinate, nudge, etc.).
type PaMonitorServer interface {
	// GetState returns a snapshot of the daemon's current state.
	GetState(context.Context, *GetStateRequest) (*DaemonState, error)
	// WatchState streams DaemonState updates. The daemon pushes a fresh
	// state on every tick (interval requested via push_interval_ms, with
	// a 250ms server floor and a 2s default). Each push is a full DB
	// materialization, so the floor bounds the worst-case snapshot rate a
	// single client can force. Subscribers detect a hung daemon by missing
	// pushes within their own watchdog budget.
	WatchState(*WatchStateRequest, grpc.ServerStreamingServer[DaemonState]) error
	// Ping is a cheap liveness check used by clients to confirm the daemon
	// is responsive before issuing a heavier RPC.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Caffeinate toggles the caffeinate manager. Result reflects the new
	// state. Persisted to runtime.json.
	Caffeinate(context.Context, *CaffeinateRequest) (*CaffeinateResponse, error)
	// IsAnyBusy returns whether any agent is currently in the working
	// state. Powers the `agents-busy-check` CLI subcommand.
	IsAnyBusy(context.Context, *IsAnyBusyRequest) (*IsAnyBusyResponse, error)
	// GetSessionInfo returns detailed state about one session.
	GetSessionInfo(context.Context, *GetSessionInfoRequest) (*SessionDetail, error)
	// GetPathInfo returns the directory rollup for a workspace path.
	GetPathInfo(context.Context, *GetPathInfoRequest) (*PathRollup, error)
	// NudgeQueue enqueues a nudge to be sent when a session next becomes idle.
	NudgeQueue(context.Context, *NudgeQueueRequest) (*NudgeQueueResponse, error)
	// NudgeCancel cancels a previously queued nudge.
	NudgeCancel(context.Context, *NudgeCancelRequest) (*NudgeCancelResponse, error)
	// SetAutoResume toggles the auto-resume feature daemon-wide.
	SetAutoResume(context.Context, *SetAutoResumeRequest) (*SetAutoResumeResponse, error)
	// RegisterBridge announces a cmux-bridge to the daemon. Called by
	// cmux-bridge on startup and as a periodic heartbeat. The daemon uses
	// bridge_pid to derive the bridge's cmux server (parent ancestor named
	// "cmux") and tracks last-seen so it can surface session terminal status
	// (cmux vs. cmux-no-bridge vs. cmux-bridge-disconnected) for sessions in
	// the same cmux workspace.
	RegisterBridge(context.Context, *RegisterBridgeRequest) (*RegisterBridgeResponse, error)
	// BridgeChannel is a bidirectional stream between a cmux-bridge and the
	// daemon: the bridge sends Register/Heartbeat/DeliverResult messages, and
	// the daemon pushes DaemonState snapshots and Deliver (nudge delivery)
	// requests.
	BridgeChannel(grpc.BidiStreamingServer[BridgeMsg, DaemonMsg]) error
	mustEmbedUnimplementedPaMonitorServer()
}

// UnimplementedPaMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaMonitorServer struct{}

func (UnimplementedPaMonitorServer) GetState(context.Context, *GetStateRequest) (*DaemonState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedPaMonitorServer) WatchState(*WatchStateRequest, grpc.ServerStreamingServer[DaemonState]) error {
	return status.Error(codes.Unimplemented, "method WatchState not implemented")
}
func (UnimplementedPaMonitorServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPaMonitorServer) Caffeinate(context.Context, *CaffeinateRequest) (*CaffeinateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Caffeinate not implemented")
}
func (UnimplementedPaMonitorServer) IsAnyBusy(context.Context, *IsAnyBusyRequest) (*IsAnyBusyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsAnyBusy not implemented")
}
func (UnimplementedPaMonitorServer) GetSessionInfo(context.Context, *GetSessionInfoRequest) (*SessionDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionInfo not implemented")
}
func (UnimplementedPaMonitorServer) GetPathInfo(context.Context, *GetPathInfoRequest) (*PathRollup, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPathInfo not implemented")
}
func (UnimplementedPaMonitorServer) NudgeQueue(context.Context, *NudgeQueueRequest) (*NudgeQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NudgeQueue not implemented")
}
func (UnimplementedPaMonitorServer) NudgeCancel(context.Context, *NudgeCancelRequest) (*NudgeCancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NudgeCancel not implemented")
}
func (UnimplementedPaMonitorServer) SetAutoResume(context.Context, *SetAutoResumeRequest) (*SetAutoResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAutoResume not implemented")
}
func (UnimplementedPaMonitorServer) RegisterBridge(context.Context, *RegisterBridgeRequest) (*RegisterBridgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterBridge not implemented")
}
func (UnimplementedPaMonitorServer) BridgeChannel(grpc.BidiStreamingServer[BridgeMsg, DaemonMsg]) error {
	return status.Error(codes.Unimplemented, "method BridgeChannel not implemented")
}
func (UnimplementedPaMonitorServer) mustEmbedUnimplementedPaMonitorServer() {}
func (UnimplementedPaMonitorServer) testEmbeddedByValue()                   {}

// UnsafePaMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaMonitorServer will
// result in compilation errors.
type UnsafePaMonitorServer interface {
	mustEmbedUnimplementedPaMonitorServer()
}

func RegisterPaMonitorServer(s grpc.ServiceRegistrar, srv PaMonitorServer) {
	// If the following call panics, it indicates UnimplementedPaMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaMonitor_ServiceDesc, srv)
}

func _PaMonitor_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaMonitor_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_WatchState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PaMonitorServer).WatchState(m, &grpc.GenericServerStream[WatchStateRequest, DaemonState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PaMonitor_WatchStateServer = grpc.ServerStreamingServer[DaemonState]

func _PaMonitor_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaMonitor_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_Caffeinate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaffeinateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).Caffeinate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaMonitor_Caffeinate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).Caffeinate(ctx, req.(*CaffeinateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_IsAnyBusy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAnyBusyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).IsAnyBusy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaMonitor_IsAnyBusy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).IsAnyBusy(ctx, req.(*IsAnyBusyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_GetSessionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).GetSessionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaMonitor_GetSessionInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).GetSessionInfo(ctx, req.(*GetSessionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_GetPathInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPathInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).GetPathInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaMonitor_GetPathInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).GetPathInfo(ctx, req.(*GetPathInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_NudgeQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NudgeQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).NudgeQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaMonitor_NudgeQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).NudgeQueue(ctx, req.(*NudgeQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_NudgeCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NudgeCancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).NudgeCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaMonitor_NudgeCancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).NudgeCancel(ctx, req.(*NudgeCancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_SetAutoResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAutoResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).SetAutoResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaMonitor_SetAutoResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).SetAutoResume(ctx, req.(*SetAutoResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_RegisterBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaMonitorServer).RegisterBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaMonitor_RegisterBridge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaMonitorServer).RegisterBridge(ctx, req.(*RegisterBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaMonitor_BridgeChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PaMonitorServer).BridgeChannel(&grpc.GenericServerStream[BridgeMsg, DaemonMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PaMonitor_BridgeChannelServer = grpc.BidiStreamingServer[BridgeMsg, DaemonMsg]

// PaMonitor_ServiceDesc is the grpc.ServiceDesc for PaMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pa_monitor.v1.PaMonitor",
	HandlerType: (*PaMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _PaMonitor_GetState_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _PaMonitor_Ping_Handler,
		},
		{
			MethodName: "Caffeinate",
			Handler:    _PaMonitor_Caffeinate_Handler,
		},
		{
			MethodName: "IsAnyBusy",
			Handler:    _PaMonitor_IsAnyBusy_Handler,
		},
		{
			MethodName: "GetSessionInfo",
			Handler:    _PaMonitor_GetSessionInfo_Handler,
		},
		{
			MethodName: "GetPathInfo",
			Handler:    _PaMonitor_GetPathInfo_Handler,
		},
		{
			MethodName: "NudgeQueue",
			Handler:    _PaMonitor_NudgeQueue_Handler,
		},
		{
			MethodName: "NudgeCancel",
			Handler:    _PaMonitor_NudgeCancel_Handler,
		},
		{
			MethodName: "SetAutoResume",
			Handler:    _PaMonitor_SetAutoResume_Handler,
		},
		{
			MethodName: "RegisterBridge",
			Handler:    _PaMonitor_RegisterBridge_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchState",
			Handler:       _PaMonitor_WatchState_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BridgeChannel",
			Handler:       _PaMonitor_BridgeChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/pa_monitor.proto",
}
