package parity

import (
	"fmt"
	"sort"
	"strings"
)

// fakeConnectorScript renders the fixture-driven fake pg-connector: a POSIX
// shell script that answers, from the fixture, exactly the calls the two
// pg-desk sides make while loading it. Every call (answered or not) is appended
// to callLog first, so the harness can prove the fake and not some real
// pg-connector was reached.
//
// The calls, read from internal/gather (the pre-cutover Gather and the generic
// entity seam's pr and issue adapters) of the pg-desk binary:
//
//	pr show <id> [--fresh]                    the PR (exit 4 when unknown)
//	pr files <id>, pr commits <id>            the PR's files and commits
//	ci list <id>                              the CI runs (bare fan-out answer)
//	issue list --query work-beads             every fixture bead, or only the open
//	                                          ones when the fixture sets
//	                                          work_beads_open_only (bare)
//	issue list --query pending-review-escalations   none (bare)
//	issue show <bead id> [--fresh]            one bead (exit 4 when unknown)
//	issue deps <bead id> --full               no dependencies
//	pr review pending <id>                    no pending review
//
// Anything else gets an "unsupported" error envelope and exit 1, never an
// invented answer. `pr list`/`pr changes` are deliberately absent: the runners
// hydrate with `pg-desk <type> refresh`, never the pull-through `changes` verb.
func fakeConnectorScript(fx *Fixture, callLog string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# fake pg-connector, generated by internal/parity from the scenario " + fx.Name + ".\n")
	b.WriteString("# It answers only from the fixture and logs every call.\n")
	fmt.Fprintf(&b, "printf '%%s\\n' \"$*\" >> %s\n", shellQuote(callLog))
	b.WriteString("case \"$*\" in\n")

	emit := func(args string, body []byte) {
		fmt.Fprintf(&b, "%s)\n  printf '%%s\\n' %s\n  exit 0;;\n", shellQuote(args), shellQuote(string(body)))
	}
	// notFound takes a case pattern already in shell syntax (a quoted prefix
	// followed by a glob), so a call for an id the fixture lacks exits 4.
	notFound := func(pattern string) {
		fmt.Fprintf(&b, "%s)\n  exit 4;;\n", pattern)
	}

	for _, p := range fx.PRs {
		id := entityID(p.Number)
		emit("pr show "+id, wireEnvelope(fx.prShowJSON(p)))
		emit("pr show "+id+" --fresh", wireEnvelope(fx.prShowJSON(p)))
		emit("pr files "+id, wireEnvelope(fx.prFilesJSON(p)))
		emit("pr commits "+id, wireEnvelope(fx.prCommitsJSON(p)))
		emit("ci list "+id, fx.ciListJSON(p))
		emit("pr review pending "+id, wireEnvelope(fx.reviewPendingJSON(p)))
	}
	beads := append([]BeadFixture(nil), fx.Beads...)
	sort.Slice(beads, func(i, j int) bool { return beads[i].ID < beads[j].ID })
	for _, bd := range beads {
		emit("issue show "+bd.ID, wireEnvelope(fx.issueShowJSON(bd)))
		emit("issue show "+bd.ID+" --fresh", wireEnvelope(fx.issueShowJSON(bd)))
		emit("issue deps "+bd.ID+" --full", wireEnvelope(fx.issueDepsJSON(bd)))
	}
	emit("issue list --query work-beads", fx.workBeadsJSON())
	emit("issue list --query pending-review-escalations", fx.escalationsJSON())

	// An unknown PR or bead is "not found" (exit 4) for a targeted read, and an
	// empty answer for a fan-out one.
	notFound("'pr show '*")
	notFound("'pr files '*")
	notFound("'pr commits '*")
	notFound("'issue show '*")
	b.WriteString("'ci list '*)\n  printf '%s\\n' '{\"runs\":[],\"sources\":[]}'\n  exit 0;;\n")
	b.WriteString("*)\n")
	b.WriteString("  printf '%s\\n' \"{\\\"error\\\":{\\\"code\\\":\\\"unsupported\\\",\\\"message\\\":\\\"fake pg-connector: unsupported call: $*\\\"}}\"\n")
	b.WriteString("  exit 1;;\n")
	b.WriteString("esac\n")
	return b.String()
}

// shellQuote quotes s as one POSIX single-quoted word.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
