{ ... }:
{
  imports = [
    ./programs/claude
    ./programs/claude-settings
    ./programs/claude-status-line
    ./programs/claude-theme
    ./programs/pgii-local-plugins
    ./programs/pgii-claude-plugins
    ./programs/pgii-packs
    ./programs/agent-rules
    ./programs/bash-scripting
    ./programs/bead-grooming
    ./programs/agentsview
    ./programs/ccusage
    ./programs/ollama
    ./programs/opencode
    ./programs/tuicr
    ./programs/neovim-claude
    ./programs/cmux-claude
    ./programs/agent-activity
    ./programs/bash-lsp
    ./programs/claude-activity
    ./programs/pa-monitor
    ./programs/ccpool
    ./programs/gc-dolt-maintenance
    ./programs/claude-extended-tool-approver
    ./programs/git-tools
    ./programs/pg-pr
    ./programs/pg-pr-plugin
    ./programs/wait-for-agents
    ./programs/beads
    ./programs/serena
    ./programs/pw-reset-agents
    ./programs/pw-agent-activity
  ];
}
