{ ... }:
{
  imports = [
    ./programs/claude-code
    ./programs/claude-settings
    ./programs/claude-status-line
    ./programs/claude-theme
    ./programs/pgii-claude-plugins
    ./programs/claude-marketplaces
    ./programs/agent-rules
    ./programs/agentsview
    ./programs/ccusage
    ./programs/codeburn
    ./programs/ollama
    ./programs/opencode
    ./programs/tuicr
    ./programs/neovim-claude
    ./programs/cmux-claude
    ./programs/agent-activity
    ./programs/claude-activity
    ./programs/pa-monitor
    ./programs/ccpool
    ./programs/pr-pool
    ./programs/pb
    ./programs/claude-extended-tool-approver
    ./programs/git-tools
    ./programs/pg-pr
    ./programs/integrate-branch-support
    ./programs/pnwf
    ./programs/wait-for-agents
    ./programs/beads
    ./programs/serena
    ./programs/pw-reset-agents
    ./programs/pw-agent-activity
    # Relocated from nix-personal (Plan 5): agent tooling belongs here.
    ./programs/perles
    ./programs/rtk
  ];
}
