{ ... }:
{
  imports = [
    ./programs/claude
    ./programs/claude-settings
    ./programs/claude-status-line
    ./programs/claude-theme
    ./programs/pgii-local-plugins
    ./programs/pgii-claude-plugins
    ./programs/agent-rules
    ./programs/bash-scripting
    ./programs/agentsview
    ./programs/ccusage
    ./programs/ollama
    ./programs/opencode
    ./programs/tuicr
    ./programs/neovim-claude
    ./programs/cmux-claude
    ./programs/agent-activity
    ./programs/bash-lsp
    ./programs/claude-activity
    ./programs/claude-agents-tui
    ./programs/claude-extended-tool-approver
    ./programs/gh-prreview
    ./programs/git-tools
    ./programs/my-code-review-support
    ./programs/wait-for-agents
    ./programs/beads
    ./programs/serena
  ];
}
