package transcript

import (
	"os"
	"strings"
	"testing"
)

func writeTestFile(path, body string) error { return os.WriteFile(path, []byte(body), 0o600) }

func TestFirstPromptFromFixture(t *testing.T) {
	got, err := FirstPrompt("../../tests/fixtures/transcripts/basic.jsonl")
	if err != nil {
		t.Fatal(err)
	}
	want := "fix the bug in login"
	if got != want {
		t.Errorf("FirstPrompt = %q, want %q", got, want)
	}
}

func TestFirstPromptSkipsToolResultUsers(t *testing.T) {
	path := t.TempDir() + "/t.jsonl"
	body := `{"type":"user","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"x","content":"ignore"}]}}
{"type":"user","message":{"role":"user","content":"real prompt"}}
`
	if err := writeTestFile(path, body); err != nil {
		t.Fatal(err)
	}
	got, err := FirstPrompt(path)
	if err != nil {
		t.Fatal(err)
	}
	if got != "real prompt" {
		t.Errorf("FirstPrompt = %q, want \"real prompt\"", got)
	}
}

func TestCleanPromptTextExtractsCommandArgs(t *testing.T) {
	in := "<command-message>/my-skill</command-message>\n" +
		"<command-name>my-skill</command-name>\n" +
		"<command-args>fix the login bug</command-args>"
	want := "fix the login bug"
	if got := cleanPromptText(in); got != want {
		t.Errorf("cleanPromptText = %q, want %q", got, want)
	}
}

// Regression: prose that merely *mentions* <command-args> (e.g. a plan file
// showing the envelope as an example) must not be mis-extracted. The
// previous implementation scanned for <command-args> anywhere in the string
// and returned a stray tag body — here the example placeholder "…" — as if
// it were the user's real prompt.
func TestCleanPromptTextIgnoresCommandArgsMentionedInProse(t *testing.T) {
	in := "Implement the following plan:\n\n" +
		"## Envelope example\n\n" +
		"Slash commands wrap arguments in `<command-args>…</command-args>` tags."
	got := cleanPromptText(in)
	if got == "…" {
		t.Fatalf("cleanPromptText collapsed prose to a single tag body: %q", got)
	}
	if !strings.HasPrefix(got, "Implement the following plan:") {
		t.Errorf("cleanPromptText = %q, want prose starting with Implement…", got)
	}
}

func TestCleanPromptTextStripsEnvelopeTags(t *testing.T) {
	in := "hello there\n\n<system-reminder>internal note you never typed</system-reminder>\n\nsecond line"
	got := cleanPromptText(in)
	if strings.Contains(got, "<system-reminder>") || strings.Contains(got, "internal note") {
		t.Errorf("cleanPromptText leaked system-reminder: %q", got)
	}
	if !strings.Contains(got, "hello there") || !strings.Contains(got, "second line") {
		t.Errorf("cleanPromptText dropped real text: %q", got)
	}
}

func TestCleanPromptTextHandlesMultilineReminderBlock(t *testing.T) {
	in := "<system-reminder>\nfirst\nsecond\nthird\n</system-reminder>actual prompt"
	want := "actual prompt"
	if got := cleanPromptText(in); got != want {
		t.Errorf("cleanPromptText = %q, want %q", got, want)
	}
}

func TestFirstPromptStripsTagsEndToEnd(t *testing.T) {
	path := t.TempDir() + "/t.jsonl"
	body := `{"type":"user","message":{"role":"user","content":"<command-message>/foo</command-message>\n<command-name>foo</command-name>\n<command-args>do the thing</command-args>"}}` + "\n"
	if err := writeTestFile(path, body); err != nil {
		t.Fatal(err)
	}
	got, err := FirstPrompt(path)
	if err != nil {
		t.Fatal(err)
	}
	if got != "do the thing" {
		t.Errorf("FirstPrompt = %q, want \"do the thing\"", got)
	}
}

func TestCleanPromptTextStripsLocalCommandCaveat(t *testing.T) {
	in := "<local-command-caveat>Caveat: The messages below were generated by the user while in a local shell.</local-command-caveat>actual prompt"
	want := "actual prompt"
	if got := cleanPromptText(in); got != want {
		t.Errorf("cleanPromptText = %q, want %q", got, want)
	}
}

func TestFirstPromptSkipsXMLOnlyEvents(t *testing.T) {
	path := t.TempDir() + "/t.jsonl"
	// First user event is raw XML that survives stripping; second is clean.
	body := `{"type":"user","message":{"role":"user","content":"<unknown-injected-tag>internal stuff</unknown-injected-tag>"}}` + "\n" +
		`{"type":"user","message":{"role":"user","content":"real prompt"}}` + "\n"
	if err := writeTestFile(path, body); err != nil {
		t.Fatal(err)
	}
	got, err := FirstPrompt(path)
	if err != nil {
		t.Fatal(err)
	}
	if got != "real prompt" {
		t.Errorf("FirstPrompt = %q, want \"real prompt\"", got)
	}
}
