schema = 3
cachePackages = [
  'github.com/BurntSushi/toml',
  'github.com/spf13/pflag'
]

[mod]
  [mod.'github.com/BurntSushi/toml']
    version = 'v1.6.0'
    hash = 'sha256-ptdUJvuc21ixeLt+M5way/na3aCnCO4MYHWulWp8NEY='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.5'
    hash = 'sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw='
