package legacyextract

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/phillipgreenii/claude-extended-tool-approver/internal/goldencorpus"
)

// WriteCorpus writes rows (the legacy-tagged extraction) to path as a JSON
// array in goldencorpus.Row's own field order -- run this repo's formatter
// (treefmt/prettier) over the result before committing; this is plain
// json.MarshalIndent output, not prettier-canonical.
func WriteCorpus(path string, rows []goldencorpus.Row) error {
	data, err := json.MarshalIndent(rows, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return os.WriteFile(path, data, 0o644)
}

// WriteDispositionReport writes the docket's own disposition report
// (extraction ratio, remainder, manual-disposition-per-family inventory,
// and the legacy-vs-new disagreement breakdown) to path as Markdown -- run
// this repo's formatter (treefmt/prettier) over the result before
// committing.
func WriteDispositionReport(path string, res *Result, cmp *CompareResult) error {
	var b strings.Builder
	fmt.Fprintf(&b, "# Legacy RuleChain/internal-rules extraction: disposition report\n\n")
	fmt.Fprintf(&b, "Generated by `go test ./internal/legacyextract/... -run TestLegacyExtract` "+
		"(docket tc-o14i5.1.3, packet \"Phase 0.3: Legacy RuleChain/internal-rules test extraction into corpus\"). "+
		"Regenerate this file with `LEGACYEXTRACT_WRITE=1 go test ./internal/legacyextract/... -run TestLegacyExtract` "+
		"or `go run ./cmd/legacyextract -write`, then run this repo's formatter before committing; do not hand-edit.\n\n")

	fmt.Fprintf(&b, "## Extraction ratio (exit criterion)\n\n")
	fmt.Fprintf(&b, "The docket design's own recount instruction: \"the implementer MUST re-count the "+
		"actual table-driven test-case total by direct inspection ... rather than trust the heuristic "+
		"figure at face value\" -- the ~2,969 figure (rules/* ~2,222 + engine ~747) is NOT the denominator "+
		"used below. This converter's own recount, by direct AST inspection (see package doc comment for "+
		"the exact two idioms recognised), is:\n\n")
	fmt.Fprintf(&b, "- Files scanned: %d\n", res.Stats.FilesScanned)
	fmt.Fprintf(&b, "- Recognised tables (idiom A batches + idiom B struct tables): %d\n", res.Stats.RecognisedTables)
	fmt.Fprintf(&b, "- Denominator (elements across every recognised table): %d\n", res.Stats.Denominator)
	fmt.Fprintf(&b, "- Extracted (converted to a corpus row): %d\n", res.Stats.Extracted)
	fmt.Fprintf(&b, "- Unconvertible rows (recognised table, element not statically resolvable): %d\n", res.Stats.UnconvertibleRows)
	fmt.Fprintf(&b, "- **Ratio: %.4f** (exit bar: >= 0.95)\n\n", res.Stats.Ratio())
	if res.Stats.Ratio() < 0.95 {
		fmt.Fprintf(&b, "**Below the 95%% exit bar.** Per the docket design's own acceptance criterion "+
			"(\"or the shortfall is explicitly listed as remainder\"), the remainder is listed below "+
			"rather than force-converting it.\n\n")
	}

	fmt.Fprintf(&b, "## Remainder: unrecognised tables (neither numerator nor denominator)\n\n")
	fmt.Fprintf(&b, "A for-range loop over a literal slice that this converter's two recognised idioms "+
		"(see package doc comment) could not classify at all. %d such loops, grouped by reason:\n\n", len(res.UnrecognisedTables))
	writeGroupedCounts(&b, res.UnrecognisedTables, func(u UnrecognisedTable) string { return u.Reason })

	fmt.Fprintf(&b, "\n## Remainder: unconvertible rows inside a recognised table\n\n")
	fmt.Fprintf(&b, "An element of a table this converter DID recognise, whose command or decision value "+
		"was not statically resolvable (built via a variable, a format helper, or another indirection "+
		"this converter's bounded call-chain resolver -- max depth %d -- did not follow). %d such rows, "+
		"grouped by reason:\n\n", maxChainDepth, len(res.UnconvertibleRows))
	writeGroupedCounts(&b, res.UnconvertibleRows, func(u UnconvertibleRow) string { return u.Reason })

	fmt.Fprintf(&b, "\n## Manual-disposition-per-family carve-out (fakes/stubs, tempdir state)\n\n")
	fmt.Fprintf(&b, "Docket design, Phase 0 item 3 (verbatim): \"Rows depending on rule-level fakes/stubs "+
		"(10 of 57 rules/* test files define fakes; 14 build tempdir state) are dispositioned manually "+
		"per family.\" This converter's own recount, via the packet's own mechanical hint (`type "+
		"[Ff]ake|type .*Stub\\b` / `t.TempDir\\(\\)|ioutil.TempDir`):\n\n")
	fmt.Fprintf(&b, "- Files matching a fake/stub type declaration: %d\n", len(res.FakeStubFiles))
	fmt.Fprintf(&b, "- Files matching tempdir construction: %d\n\n", len(res.TempDirFiles))
	fmt.Fprintf(&b, "Note: the tempdir count matches the design's cited \"14\" exactly (counting `internal/rules/*` "+
		"only; this report's totals above also include `internal/engine`, hence the slightly higher raw "+
		"numbers). The fake/stub count does NOT match the design's cited \"10\" -- several patterns were "+
		"tried (`type [Ff]ake\\w*|type \\w*Stub\\b`, a looser `type \\w*([Ff]ake|Stub)\\w*`, a bare "+
		"case-insensitive `fake` substring, `httptest.NewServer`) and the highest count found across "+
		"`internal/rules/*` alone was 4 files (envvars, kubectl, killshell, buildtools), not 10 -- the "+
		"same \"do not trust the heuristic figure at face value\" caution the packet applies to the "+
		"~2,969 row estimate evidently also applies to this count; this section reports the actual "+
		"pattern-matched files rather than force-matching the cited total.\n\n")
	fmt.Fprintf(&b, "These files' tables ARE still attempted by the same two idioms above (a file can have "+
		"some mechanically-extractable rows and still need per-family manual disposition for its "+
		"fake/stub-dependent cases) -- listed here for the manual reviewer, grouped by family:\n\n")
	writeFamilyList(&b, "Fake/stub files", res.FakeStubFiles)
	writeFamilyList(&b, "Tempdir files", res.TempDirFiles)

	fmt.Fprintf(&b, "\n## Legacy-vs-new disagreements (acceptance criterion: each resolved into one of three buckets)\n\n")
	fmt.Fprintf(&b, "Every extracted Bash/Write/Edit/MultiEdit row was run through the SAME production "+
		"`claudecodeadapter.Evaluate` chain (`cmddesc.DefaultRegistry()`, `effectpolicy.DefaultPolicies()`, "+
		"`effectpolicy.DefaultGraphPolicies()`) with a zero-value `RequestConfig` (matching the row's own "+
		"empty Settings/RulesConfig fixture), and compared against the row's own (legacy) expected_verdict.\n\n")
	fmt.Fprintf(&b, "- Comparable (Bash or a file-edit tool the adapter models): %d\n", cmp.Comparable)
	fmt.Fprintf(&b, "- Not comparable (adapter has no opinion on this tool, or refused the input outright): %d\n", cmp.NotComparable)
	fmt.Fprintf(&b, "- Agreed: %d\n", cmp.Agreed)
	fmt.Fprintf(&b, "- Disagreed: %d\n\n", len(cmp.Disagreements))

	byDisp := map[string]int{}
	for _, d := range cmp.Disagreements {
		byDisp[d.Disposition]++
	}
	fmt.Fprintf(&b, "Disposition breakdown:\n\n")
	for _, key := range []string{"old was a hole", "new too strict", "accepted change", "comparison artifact (not a genuine disagreement)", "needs manual review"} {
		if byDisp[key] > 0 {
			fmt.Fprintf(&b, "- %s: %d\n", key, byDisp[key])
		}
	}
	fmt.Fprintf(&b, "\n**Methodology and its limitations** (read before trusting the \"new too strict\" "+
		"and \"comparison artifact\" buckets below):\n\n"+
		"- `accepted change`: same restrictiveness rank (Approve < NotApprove < Reject), different "+
		"verdict spelling. Structurally cannot fire today, since both old and new verdicts are already "+
		"mapped into the corpus's own 3-value Verdict before comparison (a rank tie implies verdict "+
		"equality) -- kept for a future engine whose comparison space is richer than 3 values.\n"+
		"- `comparison artifact (not a genuine disagreement)`: the new engine's reason cites operator "+
		"configuration (vetted hosts, kube contexts, remote paths) this comparison pass never populates "+
		"(RequestConfig is zero-value, matching every row's own empty RulesConfig fixture). These are "+
		"NOT resolved into one of the three named buckets -- they are a known limitation of running this "+
		"comparison unconfigured, not a legacy-vs-new policy finding.\n"+
		"- `new too strict` (spec/policy work): the new engine's reason cites a registry/policy COVERAGE "+
		"gap -- no cmddesc schema for the command, an unmodeled subcommand/operand/flag, an "+
		"assignment-only expression with \"no executable\" to judge, or an entire command approved "+
		"outright (\"all N command nodes permitted\") because the specific family's policy (primarycommit/"+
		"primarypush/gitdir-write-protection/etc.) has not been ported into `effectpolicy.DefaultPolicies` "+
		"yet. R1 states the effect engine REPLACES RuleChain, but the per-family RETARGET (porting each "+
		"rule family's domain knowledge into cmddesc schemas and effectpolicy policies) is explicitly "+
		"later-phase work, not this packet's -- so this bucket is used for BOTH symptom directions (the "+
		"new engine looking too strict on an unmodeled tool, or too permissive on a not-yet-ported "+
		"policy), because the root cause and the remedy (add the missing schema/policy) are identical "+
		"either way. A reviewer relying on verdict direction alone should read each row's own Rationale, "+
		"which always states the literal old/new verdicts.\n"+
		"- `needs manual review`: a genuine strictness delta with no mechanically-diagnosable cause -- "+
		"resolve into \"old was a hole\" vs \"new too strict\" by reading the actual command.\n\n")

	fmt.Fprintf(&b, "### Disagreements by family (old -> new)\n\n")
	byPattern := map[string]int{}
	for _, d := range cmp.Disagreements {
		byPattern[fmt.Sprintf("%s: %s -> %s", d.Family, d.OldVerdict, d.NewVerdict)]++
	}
	writeCountMap(&b, byPattern)

	fmt.Fprintf(&b, "\n### `needs manual review` rows (full list -- the packet's own actual remainder for this criterion)\n\n")
	fmt.Fprintf(&b, "| case | family | command | old -> new | new reason |\n|---|---|---|---|---|\n")
	var review []Disagreement
	for _, d := range cmp.Disagreements {
		if d.Disposition == "needs manual review" {
			review = append(review, d)
		}
	}
	sort.Slice(review, func(i, j int) bool { return review[i].Case < review[j].Case })
	for _, d := range review {
		fmt.Fprintf(&b, "| %s | %s | `%s` | %s -> %s | %s |\n",
			d.Case, d.Family, mdEscape(d.Command), d.OldVerdict, d.NewVerdict, mdEscape(d.NewReason))
	}

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func mdEscape(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

func writeGroupedCounts[T any](b *strings.Builder, items []T, reasonOf func(T) string) {
	counts := map[string]int{}
	for _, it := range items {
		counts[reasonOf(it)]++
	}
	writeCountMap(b, counts)
}

func writeCountMap(b *strings.Builder, counts map[string]int) {
	type kv struct {
		k string
		v int
	}
	var kvs []kv
	for k, v := range counts {
		kvs = append(kvs, kv{k, v})
	}
	sort.Slice(kvs, func(i, j int) bool {
		if kvs[i].v != kvs[j].v {
			return kvs[i].v > kvs[j].v
		}
		return kvs[i].k < kvs[j].k
	})
	for _, e := range kvs {
		fmt.Fprintf(b, "- %d: %s\n", e.v, e.k)
	}
}

func writeFamilyList(b *strings.Builder, title string, files []FlaggedFile) {
	byFamily := map[string][]string{}
	for _, f := range files {
		byFamily[f.Family] = append(byFamily[f.Family], f.File)
	}
	var families []string
	for f := range byFamily {
		families = append(families, f)
	}
	sort.Strings(families)
	fmt.Fprintf(b, "%s (%d families):\n\n", title, len(families))
	for _, fam := range families {
		files := byFamily[fam]
		sort.Strings(files)
		fmt.Fprintf(b, "- **%s**: %s\n", fam, strings.Join(files, ", "))
	}
	fmt.Fprintf(b, "\n")
}
