schema = 3

[mod]
  [mod.'github.com/dustin/go-humanize']
    version = 'v1.0.1'
    hash = 'sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc='

  [mod.'github.com/google/uuid']
    version = 'v1.6.0'
    hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.24'
    hash = 'sha256-pmq8KKIb2+qMF3E1cR2B7NAj5joF2tZduyXjIfIlkTk='

  [mod.'github.com/ncruces/go-strftime']
    version = 'v1.0.0'
    hash = 'sha256-GYIwYDONuv/yTE0AEugCHQbtV3oiBaco93xUNYFcVBQ='

  [mod.'github.com/remyoudompheng/bigfft']
    version = 'v0.0.0-20230129092748-24d4a6f8daec'
    hash = 'sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM='

  [mod.'github.com/spf13/cobra']
    version = 'v1.10.2'
    hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'golang.org/x/sys']
    version = 'v0.47.0'
    hash = 'sha256-TpbRyWWqHjddP6QzUgAbaLd2EE0S+GYNRUIDJd18r98='

  [mod.'modernc.org/libc']
    version = 'v1.75.3'
    hash = 'sha256-71+GTX0yxQPIbVPdsDswLOsjsujd1ZcvXzAbDpfyBGI='

  [mod.'modernc.org/mathutil']
    version = 'v1.7.1'
    hash = 'sha256-COZ5rF2GhQVR1r6a0DanJ8qwQ94JSKdQxTMWrDzE0Cc='

  [mod.'modernc.org/memory']
    version = 'v1.12.1'
    hash = 'sha256-Y/kW9/A5uF+Y66kDbxrh4muFgE3CEee6YzSl2FMPcRg='

  [mod.'modernc.org/sqlite']
    version = 'v1.57.0'
    hash = 'sha256-2qJE5zMzeodvjZ37oLfx4J/u/SpBC3/Wi6rb1Ehx0t4='

  [mod.'mvdan.cc/sh/v3']
    version = 'v3.13.1'
    hash = 'sha256-FM+2xpGELZLm4Gc09OE5Z3JeNLPMvzeb1wRcdAIeKy4='
