schema = 3
cachePackages = [
  'github.com/phillipgreenii/x/gitclient',
  'github.com/phillipgreenii/x/gitfixture',
  'github.com/phillipgreenii/x/gittest',
  'github.com/spf13/cobra',
  'github.com/spf13/pflag'
]

[mod]
  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/phillipgreenii/x']
    version = 'v0.0.0-20261007115411-386c14bc447d'
    hash = 'sha256-VOmqXfMbGimAQTkO0RdoMtjTnaxO5P3N5+R3xVHtG0w='

  [mod.'github.com/spf13/cobra']
    version = 'v1.8.1'
    hash = 'sha256-yDF6yAHycV1IZOrt3/hofR+QINe+B2yqkcIaVov3Ky8='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.5'
    hash = 'sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw='
