# Agent-tooling capabilities (Plan 5, Light model). Each leaf is a thin setter
# generated by nix-repo-base's mkCapability (feature + isHuman gating, invariants
# enforced by construction); bundles compose leaves via mkBundle. The feature
# MODULES they enable live in ./programs/* (aggregated by homeModules.default).
#
# Consumed by flake.nix's homeModules.capabilities, which threads mkCapability /
# mkBundle from nix-repo-base and imports the capability-framework alongside.
#
# NONE of these subscribe to bundles.development — agent tooling is opt-in, not
# part of the generic dev-machine set.
{ mkCapability, mkBundle }:
{
  imports =
    (map mkCapability [
      # claude-code turns on the binary/suite AND ceta (the PreToolUse approver),
      # which is default-ON wherever claude-code is; a consumer (monorepod) vetoes
      # ceta until the hook-support->ceta gate migration (tc-jizbz). ccusage is a
      # SEPARATE opt-in leaf (below), deliberately not enabled here.
      {
        name = "claude-code";
        features = [
          "claude-code"
          "claude-extended-tool-approver"
        ];
      }
      {
        name = "ccusage";
        features = [ "ccusage" ];
      }
      # perles is a human-only TUI for beads.
      {
        name = "beads";
        features = [
          "beads"
          "gc-dolt-maintenance"
        ];
        humanFeatures = [ "perles" ];
      }
      {
        name = "serena";
        features = [ "serena" ];
      }
      {
        name = "ollama";
        features = [ "ollama" ];
      }
      {
        name = "opencode";
        features = [ "opencode" ];
      }
      {
        name = "rtk";
        features = [ "rtk" ];
      }
      # PR/git helper CLIs — human PR work.
      {
        name = "pr-tools";
        humanFeatures = [
          "git-tools"
          "pg-pr"
          "pb"
        ];
      }
      # Multi-agent orchestration/fleet management.
      {
        name = "claude-fleet";
        features = [
          "ccpool"
          "pr-pool"
          "pa-monitor"
          "pw-agent-activity"
          "pw-reset-agents"
          "wait-for-agents"
          "agent-activity"
          "agentsview"
        ];
      }
    ])
    ++ (map mkBundle [
      {
        name = "agent-support";
        capabilities = [
          "claude-code"
          "beads"
        ];
      }
      {
        name = "local-agent-support";
        capabilities = [
          "ollama"
          "opencode"
        ];
      }
    ]);
}
