schema = 3

[mod]
  [mod.'git.sr.ht/~jackmordaunt/go-toast']
    version = 'v1.1.2'
    hash = 'sha256-xNlul602ezXiEiRP67VEECk2a4kW1n9aHWqa+8UKT4k='

  [mod.'github.com/BurntSushi/toml']
    version = 'v1.6.0'
    hash = 'sha256-ptdUJvuc21ixeLt+M5way/na3aCnCO4MYHWulWp8NEY='

  [mod.'github.com/dustin/go-humanize']
    version = 'v1.0.1'
    hash = 'sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc='

  [mod.'github.com/esiqveland/notify']
    version = 'v0.13.3'
    hash = 'sha256-y+WqZAtCEZacAaqxdEEE+8gh2xhiPMpwM7IUmpE6og0='

  [mod.'github.com/gen2brain/beeep']
    version = 'v0.11.2'
    hash = 'sha256-vP7oVTIHLx6LIUH7lpQjYyeOOJb6DeRkGykHkv7Vbks='

  [mod.'github.com/go-ole/go-ole']
    version = 'v1.3.0'
    hash = 'sha256-tF8t3VcV71jQ4jbPL91BwR59AKDpUAFV1waIKzkXJu8='

  [mod.'github.com/godbus/dbus/v5']
    version = 'v5.1.0'
    hash = 'sha256-xOCMJpQK3KTmHTPn/CdqI4j0eENCtMmJDgAIoYqYOEY='

  [mod.'github.com/gofrs/flock']
    version = 'v0.13.0'
    hash = 'sha256-5imm90Iqstu+PnSX9RLZMHUG7qW2KX2t3xIpZ2cXSco='

  [mod.'github.com/google/uuid']
    version = 'v1.6.0'
    hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

  [mod.'github.com/jackmordaunt/icns/v3']
    version = 'v3.0.1'
    hash = 'sha256-BBS5+lIOPn3HVBr4S15YYgvffQxy24BAOAQml4CJ2s4='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.20'
    hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='

  [mod.'github.com/ncruces/go-strftime']
    version = 'v1.0.0'
    hash = 'sha256-GYIwYDONuv/yTE0AEugCHQbtV3oiBaco93xUNYFcVBQ='

  [mod.'github.com/nfnt/resize']
    version = 'v0.0.0-20180221191011-83c6a9932646'
    hash = 'sha256-yvPV+HlDOyJsiwAcVHQkmtw8DHSXyw+cXHkigXm8rAA='

  [mod.'github.com/remyoudompheng/bigfft']
    version = 'v0.0.0-20230129092748-24d4a6f8daec'
    hash = 'sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM='

  [mod.'github.com/sergeymakinen/go-bmp']
    version = 'v1.0.0'
    hash = 'sha256-8ADMMD2M+h264VGwMxBcIBfpou/2zysdo+xtWXHf9C0='

  [mod.'github.com/sergeymakinen/go-ico']
    version = 'v1.0.0-beta.0'
    hash = 'sha256-ljOz3cREtFSoqdVtfPo2tgk25QA90Bfn/iHJYKF9roQ='

  [mod.'github.com/tadvi/systray']
    version = 'v0.0.0-20190226123456-11a2b8fa57af'
    hash = 'sha256-o0Z+nrd8l5A/CjJAW7lq5cpjdbaihfqiu5laLnSjJS8='

  [mod.'golang.org/x/sys']
    version = 'v0.42.0'
    hash = 'sha256-LhNedvUEJbPYyR6EoU91rfOr3DBBoauLOcMcyqghEos='

  [mod.'modernc.org/libc']
    version = 'v1.72.3'
    hash = 'sha256-eOCoqSnX/VzpG63nh1j3JpXRndnZZcn2cDTeutexXAI='

  [mod.'modernc.org/mathutil']
    version = 'v1.7.1'
    hash = 'sha256-COZ5rF2GhQVR1r6a0DanJ8qwQ94JSKdQxTMWrDzE0Cc='

  [mod.'modernc.org/memory']
    version = 'v1.11.0'
    hash = 'sha256-MkybF8vvrxXS5j7O8w3skwTo0aMo1yjWS0K440rYcHM='

  [mod.'modernc.org/sqlite']
    version = 'v1.52.0'
    hash = 'sha256-Y3TfO3AKxTIE2p00llUdXf8p9X5uw+EpSrwCAtO3Dyc='
